code_url = "https://github.com/opennebraska/api-localboards-org"
description = "An API for local government boards"
git_url = "git://github.com/opennebraska/api-localboards-org.git"
link_url = "api.localboards.org"
name = "api-localboards-org"
organization_name = "Open Nebraska"

[github]
archived = false
created_at = "2013-11-23T02:54:46Z"
default_branch = "master"
description = "An API for local government boards"
disabled = false
fork = false
forks_within = 10
full_name = "opennebraska/api-localboards-org"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = "api.localboards.org"
id = 14_635_125
language = "JavaScript"
license = { }
name = "api-localboards-org"
node_id = "MDEwOlJlcG9zaXRvcnkxNDYzNTEyNQ=="
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 5_042_049
  login = "opennebraska"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjUwNDIwNDk="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
