code_url = "https://github.com/opennebraska/DCparcels"
description = "Douglas County Nebraska parcel search"
git_url = "git://github.com/opennebraska/DCparcels.git"
name = "DCparcels"
organization_name = "Open Nebraska"

[github]
archived = false
created_at = "2018-08-01T20:04:03Z"
default_branch = "master"
description = "Douglas County Nebraska parcel search"
disabled = false
fork = false
forks_within = 0
full_name = "opennebraska/DCparcels"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 143_203_181
language = { }
license = { }
name = "DCparcels"
node_id = "MDEwOlJlcG9zaXRvcnkxNDMyMDMxODE="
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 5_042_049
  login = "opennebraska"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjUwNDIwNDk="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
