code_url = "https://github.com/opennebraska/free-food"
description = "Omaha area free food resources map"
git_url = "git://github.com/opennebraska/free-food.git"
link_url = "https://opennebraska.github.io/free-food/"
name = "free-food"
organization_name = "Open Nebraska"

[github]
archived = false
created_at = "2019-04-19T19:18:50Z"
default_branch = "master"
description = "Omaha area free food resources map"
disabled = false
fork = false
forks_within = 0
full_name = "opennebraska/free-food"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = true
homepage = "https://opennebraska.github.io/free-food/"
id = 182_314_278
language = "HTML"
license = { }
name = "free-food"
node_id = "MDEwOlJlcG9zaXRvcnkxODIzMTQyNzg="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 5_042_049
  login = "opennebraska"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjUwNDIwNDk="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
