code_url = "https://github.com/opennebraska/hack-lincoln"
description = "Hack Lincoln website"
git_url = "git://github.com/opennebraska/hack-lincoln.git"
link_url = "http://hacklincoln.org/"
name = "hack-lincoln"
organization_name = "Open Nebraska"

[github]
archived = false
created_at = "2014-08-13T01:25:03Z"
default_branch = "master"
description = "Hack Lincoln website"
disabled = false
fork = false
forks_within = 10
full_name = "opennebraska/hack-lincoln"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = "http://hacklincoln.org/"
id = 22_898_265
language = "CSS"
license = { }
name = "hack-lincoln"
node_id = "MDEwOlJlcG9zaXRvcnkyMjg5ODI2NQ=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 5_042_049
  login = "opennebraska"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjUwNDIwNDk="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
