code_url = "https://github.com/opennebraska/hackomaha-ops"
description = "Oops, we visualized your data again"
git_url = "git://github.com/opennebraska/hackomaha-ops.git"
name = "hackomaha-ops"
organization_name = "Open Nebraska"

[github]
archived = false
created_at = "2013-11-26T00:13:53Z"
default_branch = "master"
description = "Oops, we visualized your data again"
disabled = false
fork = true
forks_within = 0
full_name = "opennebraska/hackomaha-ops"
has_downloads = true
has_issues = false
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 14_702_468
language = "JavaScript"
name = "hackomaha-ops"
node_id = "MDEwOlJlcG9zaXRvcnkxNDcwMjQ2OA=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 5_042_049
  login = "opennebraska"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjUwNDIwNDk="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
