code_url = "https://github.com/opennebraska/intro-to-civic-hacking-ii"
description = "Workshop: An Introduction to Civic Hacking"
git_url = "git://github.com/opennebraska/intro-to-civic-hacking-ii.git"
link_url = "https://bit.ly/civichacktalk2"
name = "intro-to-civic-hacking-ii"
organization_name = "Open Nebraska"

[github]
archived = false
created_at = "2015-02-20T22:23:20Z"
default_branch = "gh-pages"
description = "Workshop: An Introduction to Civic Hacking"
disabled = false
fork = false
forks_within = 10
full_name = "opennebraska/intro-to-civic-hacking-ii"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = false
homepage = "https://bit.ly/civichacktalk2"
id = 31_088_057
language = "HTML"
license = { }
name = "intro-to-civic-hacking-ii"
node_id = "MDEwOlJlcG9zaXRvcnkzMTA4ODA1Nw=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 5_042_049
  login = "opennebraska"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjUwNDIwNDk="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
