code_url = "https://github.com/opennebraska/lincolnanswers"
description = "test repo"
git_url = "git://github.com/opennebraska/lincolnanswers.git"
link_url = "http://lincolnanswers.org/"
name = "lincolnanswers"
organization_name = "Open Nebraska"

[github]
archived = false
created_at = "2014-05-30T05:38:30Z"
default_branch = "master"
description = "test repo"
disabled = false
fork = false
forks_within = 10
full_name = "opennebraska/lincolnanswers"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = "http://lincolnanswers.org/"
id = 20_318_407
language = "CSS"
license = { }
name = "lincolnanswers"
node_id = "MDEwOlJlcG9zaXRvcnkyMDMxODQwNw=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 5_042_049
  login = "opennebraska"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjUwNDIwNDk="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
