code_url = "https://github.com/opennebraska/nadc_data"
description = "Scripts to download and parse ready-to-upload data to our Nebraska campaign finance app."
git_url = "git://github.com/opennebraska/nadc_data.git"
link_url = "https://github.com/OWH-projects/nadc_data"
name = "nadc_data"
organization_name = "Open Nebraska"

[github]
archived = false
created_at = "2019-08-09T17:21:32Z"
default_branch = "master"
description = "Scripts to download and parse ready-to-upload data to our Nebraska campaign finance app."
disabled = false
fork = true
forks_within = 10
full_name = "opennebraska/nadc_data"
has_downloads = true
has_issues = false
has_pages = false
has_projects = true
has_wiki = true
homepage = "https://github.com/OWH-projects/nadc_data"
id = 201_512_007
language = "Rich Text Format"
license = { }
name = "nadc_data"
node_id = "MDEwOlJlcG9zaXRvcnkyMDE1MTIwMDc="
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 5_042_049
  login = "opennebraska"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjUwNDIwNDk="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
