code_url = "https://github.com/opennebraska/omahapermits"
description = "Scraping omahapermits.com"
git_url = "git://github.com/opennebraska/omahapermits.git"
name = "omahapermits"
organization_name = "Open Nebraska"

[github]
archived = false
created_at = "2019-03-05T00:23:13Z"
default_branch = "master"
description = "Scraping omahapermits.com"
disabled = false
fork = false
forks_within = 0
full_name = "opennebraska/omahapermits"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 173_843_232
language = "Perl"
license = { }
name = "omahapermits"
node_id = "MDEwOlJlcG9zaXRvcnkxNzM4NDMyMzI="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 5_042_049
  login = "opennebraska"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjUwNDIwNDk="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
