code_url = "https://github.com/opennebraska/omaha-permit-scraper"
description = "a scraper for the awful Omaha Building Permit database"
git_url = "git://github.com/opennebraska/omaha-permit-scraper.git"
link_url = "https://www.omahapermits.com//permitinfo/"
name = "omaha-permit-scraper"
organization_name = "Open Nebraska"

[github]
archived = false
created_at = "2012-09-26T23:13:37Z"
default_branch = "master"
description = "a scraper for the awful Omaha Building Permit database"
disabled = false
fork = false
forks_within = 0
full_name = "opennebraska/omaha-permit-scraper"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = "https://www.omahapermits.com//permitinfo/"
id = 5_973_997
language = "Ruby"
license = { }
name = "omaha-permit-scraper"
node_id = "MDEwOlJlcG9zaXRvcnk1OTczOTk3"
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 5_042_049
  login = "opennebraska"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjUwNDIwNDk="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
