code_url = "https://github.com/opennebraska/onio-wp-theme"
description = "Open/Nebraska site - wordpress themed!"
git_url = "git://github.com/opennebraska/onio-wp-theme.git"
name = "onio-wp-theme"
organization_name = "Open Nebraska"

[github]
archived = false
created_at = "2017-05-02T01:23:26Z"
default_branch = "master"
description = "Open/Nebraska site - wordpress themed!"
disabled = false
fork = true
forks_within = 0
full_name = "opennebraska/onio-wp-theme"
has_downloads = true
has_issues = false
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 89_978_123
language = "JavaScript"
license = { }
name = "onio-wp-theme"
node_id = "MDEwOlJlcG9zaXRvcnk4OTk3ODEyMw=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 5_042_049
  login = "opennebraska"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjUwNDIwNDk="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
