code_url = "https://github.com/opennebraska/pri-tif"
description = "Nebraska TIF Report (Tax Increment Financing)"
git_url = "git://github.com/opennebraska/pri-tif.git"
link_url = "http://nebraska.tif.report"
name = "pri-tif"
organization_name = "Open Nebraska"

[github]
archived = false
created_at = "2015-08-01T16:35:31Z"
default_branch = "master"
description = "Nebraska TIF Report (Tax Increment Financing)"
disabled = false
fork = false
forks_within = 10
full_name = "opennebraska/pri-tif"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = true
homepage = "http://nebraska.tif.report"
id = 40_052_947
language = "Perl"
license = { }
name = "pri-tif"
node_id = "MDEwOlJlcG9zaXRvcnk0MDA1Mjk0Nw=="
open_issues_within = 10
private = false
pushed_within = "year"
stargazers_within = 10
topics = [ ]
updated_within = "month"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 5_042_049
  login = "opennebraska"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjUwNDIwNDk="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
