code_url = "https://github.com/opennebraska/transitparty"
description = "Visualizing the Omaha Metro transit system"
git_url = "git://github.com/opennebraska/transitparty.git"
link_url = "http://transitparty.opennebraska.io/"
name = "transitparty"
organization_name = "Open Nebraska"

[github]
archived = false
created_at = "2013-11-23T19:02:14Z"
default_branch = "master"
description = "Visualizing the Omaha Metro transit system"
disabled = false
fork = false
forks_within = 10
full_name = "opennebraska/transitparty"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = "http://transitparty.opennebraska.io/"
id = 14_648_485
language = "JavaScript"
license = { }
name = "transitparty"
node_id = "MDEwOlJlcG9zaXRvcnkxNDY0ODQ4NQ=="
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 5_042_049
  login = "opennebraska"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjUwNDIwNDk="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
