code_url = "https://github.com/opensandiego/sandiego-food-map"
git_url = "git://github.com/opensandiego/sandiego-food-map.git"
name = "sandiego-food-map"
organization_name = "Open San Diego"

[github]
archived = false
created_at = "2020-09-10T22:30:28Z"
default_branch = "master"
description = { }
disabled = false
fork = false
forks_within = 0
full_name = "opensandiego/sandiego-food-map"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 294_536_527
language = { }
license = { }
name = "sandiego-food-map"
node_id = "MDEwOlJlcG9zaXRvcnkyOTQ1MzY1Mjc="
open_issues_within = 10
private = false
pushed_within = "year"
stargazers_within = 0
topics = [ ]
updated_within = "year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 363_945
  login = "opensandiego"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjM2Mzk0NQ=="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
