code_url = "https://github.com/opendata-heilbronn/mobbing-monitor"
git_url = "git://github.com/opendata-heilbronn/mobbing-monitor.git"
name = "mobbing-monitor"
organization_name = "OK Lab Heilbronn"

[github]
archived = false
created_at = "2018-07-16T20:36:38Z"
default_branch = "master"
description = { }
disabled = false
fork = false
forks_within = 0
full_name = "opendata-heilbronn/mobbing-monitor"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 141_191_651
language = "HTML"
license = { }
name = "mobbing-monitor"
node_id = "MDEwOlJlcG9zaXRvcnkxNDExOTE2NTE="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 6_741_385
  login = "opendata-heilbronn"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY3NDEzODU="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
