code_url = "https://github.com/opendata-heilbronn/One-Axis-Farmware"
description = "A simple Farmware plugin that allows the farmbot to move one axis at a time."
git_url = "git://github.com/opendata-heilbronn/One-Axis-Farmware.git"
name = "One-Axis-Farmware"
organization_name = "OK Lab Heilbronn"

[github]
archived = false
created_at = "2019-04-22T11:12:10Z"
default_branch = "master"
description = "A simple Farmware plugin that allows the farmbot to move one axis at a time."
disabled = false
fork = false
forks_within = 0
full_name = "opendata-heilbronn/One-Axis-Farmware"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 182_765_030
language = "Python"
license = { }
name = "One-Axis-Farmware"
node_id = "MDEwOlJlcG9zaXRvcnkxODI3NjUwMzA="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 6_741_385
  login = "opendata-heilbronn"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY3NDEzODU="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
