code_url = "https://github.com/code4romania/brain-fitness-api"
description = "API for Teacher Brain Fitness app"
git_url = "git://github.com/code4romania/brain-fitness-api.git"
name = "brain-fitness-api"
organization_name = "Code for Romania: Cluj Chapter"

[github]
archived = false
created_at = "2019-11-14T16:34:32Z"
default_branch = "master"
description = "API for Teacher Brain Fitness app"
disabled = false
fork = false
forks_within = 10
full_name = "code4romania/brain-fitness-api"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 221_741_835
language = "Python"
name = "brain-fitness-api"
node_id = "MDEwOlJlcG9zaXRvcnkyMjE3NDE4MzU="
open_issues_within = 10
private = false
pushed_within = "year"
stargazers_within = 10
topics = [ ]
updated_within = "year"
watchers_within = 10

  [github.license]
  key = "mpl-2.0"
  name = "Mozilla Public License 2.0"
  node_id = "MDc6TGljZW5zZTE0"
  spdx_id = "MPL-2.0"

  [github.owner]
  gravatar_id = ""
  id = 18_010_308
  login = "code4romania"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjE4MDEwMzA4"
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
