code_url = "https://github.com/code4romania/data-portal"
description = "Data Portal - the open data community"
git_url = "git://github.com/code4romania/data-portal.git"
name = "data-portal"
organization_name = "Code for Romania: Cluj Chapter"

[github]
archived = false
created_at = "2019-01-22T12:53:45Z"
default_branch = "master"
description = "Data Portal - the open data community"
disabled = false
fork = false
forks_within = 10
full_name = "code4romania/data-portal"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 166_993_976
language = { }
license = { }
name = "data-portal"
node_id = "MDEwOlJlcG9zaXRvcnkxNjY5OTM5NzY="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 18_010_308
  login = "code4romania"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjE4MDEwMzA4"
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
