code_url = "https://github.com/code4romania/monitorizare-vot-android"
description = "Android election monitoring app - a mobile app through which commissioned observers can easily report back to their respective NGOs throughout the election day"
git_url = "git://github.com/code4romania/monitorizare-vot-android.git"
link_url = "https://votemonitor.org/"
name = "monitorizare-vot-android"
organization_name = "Code for Romania: Cluj Chapter"
topics = [
  "android",
  "civic-hacking",
  "civic-tech",
  "civictech",
  "code4ro",
  "election-data",
  "election-monitoring",
  "elections",
  "monitoring"
]

[github]
archived = false
created_at = "2016-09-26T10:35:07Z"
default_branch = "develop"
description = "Android election monitoring app - a mobile app through which commissioned observers can easily report back to their respective NGOs throughout the election day"
disabled = false
fork = false
forks_within = 100
full_name = "code4romania/monitorizare-vot-android"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = "https://votemonitor.org/"
id = 69_239_703
language = "Java"
name = "monitorizare-vot-android"
node_id = "MDEwOlJlcG9zaXRvcnk2OTIzOTcwMw=="
open_issues_within = 100
private = false
pushed_within = "year"
stargazers_within = 10
topics = [
  "android",
  "civic-hacking",
  "civic-tech",
  "civictech",
  "code4ro",
  "election-data",
  "election-monitoring",
  "elections",
  "monitoring"
]
updated_within = "year"
watchers_within = 10

  [github.license]
  key = "mpl-2.0"
  name = "Mozilla Public License 2.0"
  node_id = "MDc6TGljZW5zZTE0"
  spdx_id = "MPL-2.0"

  [github.owner]
  gravatar_id = ""
  id = 18_010_308
  login = "code4romania"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjE4MDEwMzA4"
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
