code_url = "https://github.com/code4romania/scribeAPI"
description = "Scribe is a framework for crowdsourcing the transcription of text-based documents, particularly documents that are not well suited for Optical Character Recognition."
git_url = "git://github.com/code4romania/scribeAPI.git"
name = "scribeAPI"
organization_name = "Code for Romania: Cluj Chapter"

[github]
archived = false
created_at = "2016-11-13T14:35:43Z"
default_branch = "master"
description = "Scribe is a framework for crowdsourcing the transcription of text-based documents, particularly documents that are not well suited for Optical Character Recognition."
disabled = false
fork = true
forks_within = 0
full_name = "code4romania/scribeAPI"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 73_621_367
language = "CoffeeScript"
name = "scribeAPI"
node_id = "MDEwOlJlcG9zaXRvcnk3MzYyMTM2Nw=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 18_010_308
  login = "code4romania"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjE4MDEwMzA4"
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
