code_url = "https://github.com/code4romania/seismic-risc-client"
description = "Client repo for Seismic Risc"
git_url = "git://github.com/code4romania/seismic-risc-client.git"
name = "seismic-risc-client"
organization_name = "Code for Romania: Cluj Chapter"

[github]
archived = false
created_at = "2019-11-20T17:23:14Z"
default_branch = "master"
description = "Client repo for Seismic Risc"
disabled = false
fork = false
forks_within = 100
full_name = "code4romania/seismic-risc-client"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 222_990_625
language = "JavaScript"
name = "seismic-risc-client"
node_id = "MDEwOlJlcG9zaXRvcnkyMjI5OTA2MjU="
open_issues_within = 0
private = false
pushed_within = "year"
stargazers_within = 10
topics = [ ]
updated_within = "year"
watchers_within = 10

  [github.license]
  key = "mpl-2.0"
  name = "Mozilla Public License 2.0"
  node_id = "MDc6TGljZW5zZTE0"
  spdx_id = "MPL-2.0"

  [github.owner]
  gravatar_id = ""
  id = 18_010_308
  login = "code4romania"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjE4MDEwMzA4"
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
