code_url = "https://github.com/codeforatlanta/atlanta-open-finance"
description = "Making Atlanta financial data easy to use"
git_url = "git://github.com/codeforatlanta/atlanta-open-finance.git"
name = "atlanta-open-finance"
organization_name = "Code for Atlanta"

[github]
archived = false
created_at = "2018-10-08T23:43:45Z"
default_branch = "master"
description = "Making Atlanta financial data easy to use"
disabled = false
fork = false
forks_within = 0
full_name = "codeforatlanta/atlanta-open-finance"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 152_160_664
language = { }
license = { }
name = "atlanta-open-finance"
node_id = "MDEwOlJlcG9zaXRvcnkxNTIxNjA2NjQ="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 5_956_025
  login = "codeforatlanta"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjU5NTYwMjU="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
