code_url = "https://github.com/codeforatlanta/inspectr"
git_url = "git://github.com/codeforatlanta/inspectr.git"
name = "inspectr"
organization_name = "Code for Atlanta"

[github]
archived = false
created_at = "2015-06-06T15:04:33Z"
default_branch = "master"
description = { }
disabled = false
fork = false
forks_within = 10
full_name = "codeforatlanta/inspectr"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 36_984_128
language = "Ruby"
name = "inspectr"
node_id = "MDEwOlJlcG9zaXRvcnkzNjk4NDEyOA=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 5_956_025
  login = "codeforatlanta"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjU5NTYwMjU="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
