code_url = "https://github.com/codeforatlanta/localsite"
git_url = "git://github.com/codeforatlanta/localsite.git"
name = "localsite"
organization_name = "Code for Atlanta"

[github]
archived = false
created_at = "2020-08-11T21:47:31Z"
default_branch = "master"
description = { }
disabled = false
fork = true
forks_within = 0
full_name = "codeforatlanta/localsite"
has_downloads = true
has_issues = false
has_pages = true
has_projects = true
has_wiki = true
homepage = { }
id = 286_854_389
language = "JavaScript"
license = { }
name = "localsite"
node_id = "MDEwOlJlcG9zaXRvcnkyODY4NTQzODk="
open_issues_within = 0
private = false
pushed_within = "year"
stargazers_within = 0
topics = [ ]
updated_within = "year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 5_956_025
  login = "codeforatlanta"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjU5NTYwMjU="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
