code_url = "https://github.com/lanelookout/lanelookout/issues/6"
description = "Our project seeks to improve the safety of bike lanes for cyclists in Oakland."
link_url = "https://www.lanelookout.org"
name = "LaneLookout"
organization_name = "Open Oakland"
