description = "Explaining to school communities what the Oakland Unified School District's central office does and helping them weigh in on what its function should be in the future."
name = "OUSD Budget"
organization_name = "Open Oakland"
