code_url = "https://github.com/codeforseoul/FdAS"
description = "코드포서울 노고팀의 시민편의 프로젝트입니다. Service about welfare of Seoul city, collecting various data and providing welfare services of one's own need, not everything."
git_url = "git://github.com/codeforseoul/FdAS.git"
link_url = "welfare4u.com"
name = "FdAS"
organization_name = "CodeNamu"

[github]
archived = false
created_at = "2014-08-19T12:33:39Z"
default_branch = "develop"
description = "코드포서울 노고팀의 시민편의 프로젝트입니다. Service about welfare of Seoul city, collecting various data and providing welfare services of one's own need, not everything."
disabled = false
fork = false
forks_within = 100
full_name = "codeforseoul/FdAS"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = true
homepage = "welfare4u.com"
id = 23_109_313
language = "JavaScript"
license = { }
name = "FdAS"
node_id = "MDEwOlJlcG9zaXRvcnkyMzEwOTMxMw=="
open_issues_within = 100
private = false
pushed_within = "over_a_year"
stargazers_within = 100
topics = [ ]
updated_within = "year"
watchers_within = 100

  [github.owner]
  gravatar_id = ""
  id = 7_872_447
  login = "codeforseoul"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjc4NzI0NDc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
