code_url = "https://github.com/codeforamerica/311DailyBrief"
git_url = "git://github.com/codeforamerica/311DailyBrief.git"
name = "311DailyBrief"
organization_name = "Code for America"

[github]
archived = false
created_at = "2012-04-11T21:44:53Z"
default_branch = "master"
description = { }
disabled = false
fork = false
forks_within = 10
full_name = "codeforamerica/311DailyBrief"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = true
homepage = ""
id = 3_998_674
language = "JavaScript"
name = "311DailyBrief"
node_id = "MDEwOlJlcG9zaXRvcnkzOTk4Njc0"
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 100
topics = [ ]
updated_within = "over_a_year"
watchers_within = 100

  [github.license]
  key = "bsd-2-clause"
  name = 'BSD 2-Clause "Simplified" License'
  node_id = "MDc6TGljZW5zZTQ="
  spdx_id = "BSD-2-Clause"

  [github.owner]
  gravatar_id = ""
  id = 337_792
  login = "codeforamerica"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjMzNzc5Mg=="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
