code_url = "https://github.com/codeforamerica/alaska-benefits"
description = "A simple website with instructions on how to apply for government benefits in Alaska."
git_url = "git://github.com/codeforamerica/alaska-benefits.git"
name = "alaska-benefits"
organization_name = "Code for America"

[github]
archived = false
created_at = "2019-01-25T00:23:04Z"
default_branch = "master"
description = "A simple website with instructions on how to apply for government benefits in Alaska."
disabled = false
fork = false
forks_within = 10
full_name = "codeforamerica/alaska-benefits"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 167_458_375
language = "Ruby"
name = "alaska-benefits"
node_id = "MDEwOlJlcG9zaXRvcnkxNjc0NTgzNzU="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 337_792
  login = "codeforamerica"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjMzNzc5Mg=="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
