code_url = "https://github.com/codeforamerica/awards"
description = "Code for America Technology Awards website"
git_url = "git://github.com/codeforamerica/awards.git"
link_url = "http://awards.codeforamerica.org"
name = "awards"
organization_name = "Code for America"

[github]
archived = false
created_at = "2015-06-03T21:58:25Z"
default_branch = "gh-pages"
description = "Code for America Technology Awards website"
disabled = false
fork = false
forks_within = 10
full_name = "codeforamerica/awards"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = true
homepage = "http://awards.codeforamerica.org"
id = 36_832_939
language = "HTML"
license = { }
name = "awards"
node_id = "MDEwOlJlcG9zaXRvcnkzNjgzMjkzOQ=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 337_792
  login = "codeforamerica"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjMzNzc5Mg=="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
