code_url = "https://github.com/codeforamerica/beta"
description = "Website for a tiny Code for America conference"
git_url = "git://github.com/codeforamerica/beta.git"
link_url = "http://codeforamerica.github.io/beta/"
name = "beta"
organization_name = "Code for America"

[github]
archived = false
created_at = "2014-05-23T18:58:00Z"
default_branch = "gh-pages"
description = "Website for a tiny Code for America conference"
disabled = false
fork = false
forks_within = 10
full_name = "codeforamerica/beta"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = true
homepage = "http://codeforamerica.github.io/beta/"
id = 20_110_655
language = "CSS"
name = "beta"
node_id = "MDEwOlJlcG9zaXRvcnkyMDExMDY1NQ=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 337_792
  login = "codeforamerica"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjMzNzc5Mg=="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
