code_url = "https://github.com/codeforamerica/chime"
description = "A city-focused content management system"
git_url = "git://github.com/codeforamerica/chime.git"
link_url = "http://chimecms.org/"
name = "chime"
organization_name = "Code for America"

[github]
archived = false
created_at = "2014-04-01T18:29:19Z"
default_branch = "master"
description = "A city-focused content management system"
disabled = false
fork = false
forks_within = 100
full_name = "codeforamerica/chime"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = "http://chimecms.org/"
id = 18_339_970
language = "HTML"
name = "chime"
node_id = "MDEwOlJlcG9zaXRvcnkxODMzOTk3MA=="
open_issues_within = 1_000
private = false
pushed_within = "over_a_year"
stargazers_within = 100
topics = [ ]
updated_within = "over_a_year"
watchers_within = 100

  [github.license]
  key = "bsd-3-clause"
  name = 'BSD 3-Clause "New" or "Revised" License'
  node_id = "MDc6TGljZW5zZTU="
  spdx_id = "BSD-3-Clause"

  [github.owner]
  gravatar_id = ""
  id = 337_792
  login = "codeforamerica"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjMzNzc5Mg=="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
