code_url = "https://github.com/codeforamerica/codeforamerica.github.com"
description = "Github Project Page"
git_url = "git://github.com/codeforamerica/codeforamerica.github.com.git"
name = "codeforamerica.github.com"
organization_name = "Code for America"

[github]
archived = false
created_at = "2012-02-02T06:15:13Z"
default_branch = "master"
description = "Github Project Page"
disabled = false
fork = false
forks_within = 10
full_name = "codeforamerica/codeforamerica.github.com"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = true
homepage = ""
id = 3_332_462
language = "CSS"
license = { }
name = "codeforamerica.github.com"
node_id = "MDEwOlJlcG9zaXRvcnkzMzMyNDYy"
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 337_792
  login = "codeforamerica"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjMzNzc5Mg=="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
