code_url = "https://github.com/codeforamerica/crisisresponse"
description = "A tool to help police offers respond to the needs of people in crisis."
git_url = "git://github.com/codeforamerica/crisisresponse.git"
name = "crisisresponse"
organization_name = "Code for America"

[github]
archived = false
created_at = "2016-03-30T19:35:11Z"
default_branch = "master"
description = "A tool to help police offers respond to the needs of people in crisis."
disabled = false
fork = false
forks_within = 10
full_name = "codeforamerica/crisisresponse"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 55_091_777
language = "Ruby"
license = { }
name = "crisisresponse"
node_id = "MDEwOlJlcG9zaXRvcnk1NTA5MTc3Nw=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 337_792
  login = "codeforamerica"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjMzNzc5Mg=="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
