code_url = "https://github.com/codeforamerica/evangelist-apps-script"
description = "This repo hosts the Google Apps Script that ties together the Brigade Network"
git_url = "git://github.com/codeforamerica/evangelist-apps-script.git"
name = "evangelist-apps-script"
organization_name = "Code for America"

[github]
archived = false
created_at = "2018-03-19T17:30:15Z"
default_branch = "master"
description = "This repo hosts the Google Apps Script that ties together the Brigade Network"
disabled = false
fork = false
forks_within = 0
full_name = "codeforamerica/evangelist-apps-script"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 125_895_743
language = "JavaScript"
license = { }
name = "evangelist-apps-script"
node_id = "MDEwOlJlcG9zaXRvcnkxMjU4OTU3NDM="
open_issues_within = 10
private = false
pushed_within = "year"
stargazers_within = 10
topics = [ ]
updated_within = "year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 337_792
  login = "codeforamerica"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjMzNzc5Mg=="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
