code_url = "https://github.com/codeforamerica/flexible-interview-demo"
git_url = "git://github.com/codeforamerica/flexible-interview-demo.git"
name = "flexible-interview-demo"
organization_name = "Code for America"

[github]
archived = false
created_at = "2019-06-12T18:39:25Z"
default_branch = "master"
description = { }
disabled = false
fork = false
forks_within = 10
full_name = "codeforamerica/flexible-interview-demo"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 191_625_877
language = "Ruby"
license = { }
name = "flexible-interview-demo"
node_id = "MDEwOlJlcG9zaXRvcnkxOTE2MjU4Nzc="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 337_792
  login = "codeforamerica"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjMzNzc5Mg=="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
