code_url = "https://github.com/codeforamerica/hipaa-sample-app"
description = "Sample Rails application to test HIPAA compliant hosting on AWS"
git_url = "git://github.com/codeforamerica/hipaa-sample-app.git"
name = "hipaa-sample-app"
organization_name = "Code for America"

[github]
archived = false
created_at = "2018-07-18T00:20:14Z"
default_branch = "master"
description = "Sample Rails application to test HIPAA compliant hosting on AWS"
disabled = false
fork = false
forks_within = 0
full_name = "codeforamerica/hipaa-sample-app"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 141_359_568
language = "Ruby"
license = { }
name = "hipaa-sample-app"
node_id = "MDEwOlJlcG9zaXRvcnkxNDEzNTk1Njg="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 337_792
  login = "codeforamerica"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjMzNzc5Mg=="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
