code_url = "https://github.com/codeforamerica/la_message"
description = "SMS messaging application for sending and tracking text messages in Louisiana."
git_url = "git://github.com/codeforamerica/la_message.git"
link_url = "https://message.labenefits.org"
name = "la_message"
organization_name = "Code for America"
topics = [ "integrated-benefits", "ruby-on-rails", "twilio" ]

[github]
archived = false
created_at = "2019-07-29T19:31:40Z"
default_branch = "master"
description = "SMS messaging application for sending and tracking text messages in Louisiana."
disabled = false
fork = false
forks_within = 10
full_name = "codeforamerica/la_message"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = false
homepage = "https://message.labenefits.org"
id = 199_515_224
language = "Ruby"
name = "la_message"
node_id = "MDEwOlJlcG9zaXRvcnkxOTk1MTUyMjQ="
open_issues_within = 10
private = false
pushed_within = "year"
stargazers_within = 10
topics = [ "integrated-benefits", "ruby-on-rails", "twilio" ]
updated_within = "year"
watchers_within = 10

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 337_792
  login = "codeforamerica"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjMzNzc5Mg=="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
