code_url = "https://github.com/codeforamerica/onboarding-bot"
description = "Brief new employees about onboarding activities via Slack"
git_url = "git://github.com/codeforamerica/onboarding-bot.git"
name = "onboarding-bot"
organization_name = "Code for America"

[github]
archived = false
created_at = "2016-06-15T04:33:31Z"
default_branch = "master"
description = "Brief new employees about onboarding activities via Slack"
disabled = false
fork = false
forks_within = 10
full_name = "codeforamerica/onboarding-bot"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 61_177_690
language = "JavaScript"
name = "onboarding-bot"
node_id = "MDEwOlJlcG9zaXRvcnk2MTE3NzY5MA=="
open_issues_within = 100
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 337_792
  login = "codeforamerica"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjMzNzc5Mg=="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
