code_url = "https://github.com/codeforamerica/rva-screening"
description = "Health service prescreener for sharing patient eligibility data."
git_url = "git://github.com/codeforamerica/rva-screening.git"
link_url = "http://quickscreenrva.com"
name = "rva-screening"
organization_name = "Code for America"

[github]
archived = false
created_at = "2015-03-20T17:58:39Z"
default_branch = "master"
description = "Health service prescreener for sharing patient eligibility data."
disabled = false
fork = false
forks_within = 10
full_name = "codeforamerica/rva-screening"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = "http://quickscreenrva.com"
id = 32_598_942
language = "Python"
name = "rva-screening"
node_id = "MDEwOlJlcG9zaXRvcnkzMjU5ODk0Mg=="
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "year"
watchers_within = 10

  [github.license]
  key = "bsd-3-clause"
  name = 'BSD 3-Clause "New" or "Revised" License'
  node_id = "MDc6TGljZW5zZTU="
  spdx_id = "BSD-3-Clause"

  [github.owner]
  gravatar_id = ""
  id = 337_792
  login = "codeforamerica"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjMzNzc5Mg=="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
