code_url = "https://github.com/codeforamerica/shiba"
description = "Securely Hosted Integrated Benefits Application"
git_url = "git://github.com/codeforamerica/shiba.git"
name = "shiba"
organization_name = "Code for America"

[github]
archived = false
created_at = "2020-05-06T15:35:14Z"
default_branch = "master"
description = "Securely Hosted Integrated Benefits Application"
disabled = false
fork = false
forks_within = 0
full_name = "codeforamerica/shiba"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 261_803_317
language = "JavaScript"
name = "shiba"
node_id = "MDEwOlJlcG9zaXRvcnkyNjE4MDMzMTc="
open_issues_within = 0
private = false
pushed_within = "week"
stargazers_within = 10
topics = [ ]
updated_within = "week"
watchers_within = 10

  [github.license]
  key = "other"
  name = "Other"
  node_id = "MDc6TGljZW5zZTA="
  spdx_id = "NOASSERTION"

  [github.owner]
  gravatar_id = ""
  id = 337_792
  login = "codeforamerica"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjMzNzc5Mg=="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
