code_url = "https://github.com/codeforamerica/sitemybiz"
description = "SiteMy.Biz"
git_url = "git://github.com/codeforamerica/sitemybiz.git"
name = "sitemybiz"
organization_name = "Code for America"

[github]
archived = false
created_at = "2012-04-22T19:50:53Z"
default_branch = "master"
description = "SiteMy.Biz"
disabled = false
fork = false
forks_within = 10
full_name = "codeforamerica/sitemybiz"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = true
homepage = ""
id = 4_106_617
language = { }
license = { }
name = "sitemybiz"
node_id = "MDEwOlJlcG9zaXRvcnk0MTA2NjE3"
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 337_792
  login = "codeforamerica"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjMzNzc5Mg=="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
