code_url = "https://github.com/codeforamerica/three"
description = "An easy-to-use Python wrapper for the Open311 API."
git_url = "git://github.com/codeforamerica/three.git"
link_url = "three.codeforamerica.org"
name = "three"
organization_name = "Code for America"

[github]
archived = false
created_at = "2012-02-05T15:39:34Z"
default_branch = "master"
description = "An easy-to-use Python wrapper for the Open311 API."
disabled = false
fork = false
forks_within = 100
full_name = "codeforamerica/three"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = false
homepage = "three.codeforamerica.org"
id = 3_360_183
language = "Python"
name = "three"
node_id = "MDEwOlJlcG9zaXRvcnkzMzYwMTgz"
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 100
topics = [ ]
updated_within = "over_a_year"
watchers_within = 100

  [github.license]
  key = "bsd-3-clause"
  name = 'BSD 3-Clause "New" or "Revised" License'
  node_id = "MDc6TGljZW5zZTU="
  spdx_id = "BSD-3-Clause"

  [github.owner]
  gravatar_id = ""
  id = 337_792
  login = "codeforamerica"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjMzNzc5Mg=="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
