code_url = "https://github.com/codeforamerica/vocatus"
description = "An automated advocate for patient rights"
git_url = "git://github.com/codeforamerica/vocatus.git"
name = "vocatus"
organization_name = "Code for America"

[github]
archived = false
created_at = "2015-04-15T23:06:31Z"
default_branch = "master"
description = "An automated advocate for patient rights"
disabled = false
fork = false
forks_within = 10
full_name = "codeforamerica/vocatus"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 34_023_080
language = "PHP"
name = "vocatus"
node_id = "MDEwOlJlcG9zaXRvcnkzNDAyMzA4MA=="
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 100
topics = [ ]
updated_within = "over_a_year"
watchers_within = 100

  [github.license]
  key = "apache-2.0"
  name = "Apache License 2.0"
  node_id = "MDc6TGljZW5zZTI="
  spdx_id = "Apache-2.0"

  [github.owner]
  gravatar_id = ""
  id = 337_792
  login = "codeforamerica"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjMzNzc5Mg=="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
