code_url = "https://github.com/codeforamerica/windypie"
description = "A Python port of the windy Ruby Socrata API wrapper"
git_url = "git://github.com/codeforamerica/windypie.git"
name = "windypie"
organization_name = "Code for America"

[github]
archived = false
created_at = "2012-04-14T00:30:12Z"
default_branch = "master"
description = "A Python port of the windy Ruby Socrata API wrapper"
disabled = false
fork = false
forks_within = 10
full_name = "codeforamerica/windypie"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 4_021_521
language = "Python"
name = "windypie"
node_id = "MDEwOlJlcG9zaXRvcnk0MDIxNTIx"
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.license]
  key = "bsd-2-clause"
  name = 'BSD 2-Clause "Simplified" License'
  node_id = "MDc6TGljZW5zZTQ="
  spdx_id = "BSD-2-Clause"

  [github.owner]
  gravatar_id = ""
  id = 337_792
  login = "codeforamerica"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjMzNzc5Mg=="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
