code_url = "https://github.com/CodeForFtL/BrowardElectedOfficials"
description = "Map of elected officials of cities in Broward County, Florida."
git_url = "git://github.com/CodeForFtL/BrowardElectedOfficials.git"
link_url = "http://codeforftl.org/BrowardElectedOfficials"
name = "BrowardElectedOfficials"
organization_name = "Code for Fort Lauderdale"

[github]
archived = false
created_at = "2015-10-15T18:19:29Z"
default_branch = "master"
description = "Map of elected officials of cities in Broward County, Florida."
disabled = false
fork = true
forks_within = 10
full_name = "CodeForFtL/BrowardElectedOfficials"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = true
homepage = "http://codeforftl.org/BrowardElectedOfficials"
id = 44_336_688
language = "HTML"
name = "BrowardElectedOfficials"
node_id = "MDEwOlJlcG9zaXRvcnk0NDMzNjY4OA=="
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 5_661_283
  login = "CodeForFtL"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjU2NjEyODM="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
