code_url = "https://github.com/CodeForFtL/ftlviz"
description = "Traffic visualization for the City of Fort Lauderdale."
git_url = "git://github.com/CodeForFtL/ftlviz.git"
link_url = "http://codeforftl.org/ftlviz"
name = "ftlviz"
organization_name = "Code for Fort Lauderdale"

[github]
archived = false
created_at = "2015-07-23T00:01:36Z"
default_branch = "master"
description = "Traffic visualization for the City of Fort Lauderdale."
disabled = false
fork = true
forks_within = 10
full_name = "CodeForFtL/ftlviz"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = true
homepage = "http://codeforftl.org/ftlviz"
id = 39_536_198
language = "JavaScript"
license = { }
name = "ftlviz"
node_id = "MDEwOlJlcG9zaXRvcnkzOTUzNjE5OA=="
open_issues_within = 10
private = false
pushed_within = "month"
stargazers_within = 10
topics = [ ]
updated_within = "month"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 5_661_283
  login = "CodeForFtL"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjU2NjEyODM="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
