code_url = "https://github.com/CodeForFtL/informed-voter"
git_url = "git://github.com/CodeForFtL/informed-voter.git"
name = "informed-voter"
organization_name = "Code for Fort Lauderdale"

[github]
archived = false
created_at = "2020-06-25T00:31:47Z"
default_branch = "master"
description = { }
disabled = false
fork = false
forks_within = 0
full_name = "CodeForFtL/informed-voter"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 274_797_276
language = { }
license = { }
name = "informed-voter"
node_id = "MDEwOlJlcG9zaXRvcnkyNzQ3OTcyNzY="
open_issues_within = 0
private = false
pushed_within = "year"
stargazers_within = 0
topics = [ ]
updated_within = "year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 5_661_283
  login = "CodeForFtL"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjU2NjEyODM="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
