code_url = "https://github.com/sfbrigade/c4sf.me"
description = "A url shortening service for Code for San Francisco"
git_url = "git://github.com/sfbrigade/c4sf.me.git"
link_url = "http://c4sf.me/admin"
name = "c4sf.me"
organization_name = "Code for San Francisco"

[github]
archived = false
created_at = "2016-03-01T20:14:40Z"
default_branch = "master"
description = "A url shortening service for Code for San Francisco"
disabled = false
fork = false
forks_within = 0
full_name = "sfbrigade/c4sf.me"
has_downloads = true
has_issues = true
has_pages = false
has_projects = false
has_wiki = false
homepage = "http://c4sf.me/admin"
id = 52_906_695
language = "CSS"
name = "c4sf.me"
node_id = "MDEwOlJlcG9zaXRvcnk1MjkwNjY5NQ=="
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 3_926_630
  login = "sfbrigade"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjM5MjY2MzA="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
