code_url = "https://github.com/sfbrigade/codeforsanfrancisco.org"
description = "CodeForSanFrancisco.org is hosted on Netlify and build using Jekyll"
git_url = "git://github.com/sfbrigade/codeforsanfrancisco.org.git"
link_url = "https://codeforsanfrancisco.org/"
name = "codeforsanfrancisco.org"
organization_name = "Code for San Francisco"

[github]
archived = false
created_at = "2017-11-21T03:40:52Z"
default_branch = "master"
description = "CodeForSanFrancisco.org is hosted on Netlify and build using Jekyll"
disabled = false
fork = false
forks_within = 100
full_name = "sfbrigade/codeforsanfrancisco.org"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = "https://codeforsanfrancisco.org/"
id = 111_495_239
language = "HTML"
name = "codeforsanfrancisco.org"
node_id = "MDEwOlJlcG9zaXRvcnkxMTE0OTUyMzk="
open_issues_within = 100
private = false
pushed_within = "year"
stargazers_within = 10
topics = [ ]
updated_within = "year"
watchers_within = 10

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 3_926_630
  login = "sfbrigade"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjM5MjY2MzA="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
