code_url = "https://github.com/sfbrigade/datasci-campaign-finance"
description = "C4SF Data Science Working Group Makes Campaign Finance More Transparent!"
git_url = "git://github.com/sfbrigade/datasci-campaign-finance.git"
name = "datasci-campaign-finance"
organization_name = "Code for San Francisco"

[github]
archived = false
created_at = "2017-12-14T02:22:03Z"
default_branch = "master"
description = "C4SF Data Science Working Group Makes Campaign Finance More Transparent!"
disabled = false
fork = false
forks_within = 10
full_name = "sfbrigade/datasci-campaign-finance"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 114_191_707
language = "Jupyter Notebook"
license = { }
name = "datasci-campaign-finance"
node_id = "MDEwOlJlcG9zaXRvcnkxMTQxOTE3MDc="
open_issues_within = 100
private = false
pushed_within = "year"
stargazers_within = 100
topics = [ ]
updated_within = "year"
watchers_within = 100

  [github.owner]
  gravatar_id = ""
  id = 3_926_630
  login = "sfbrigade"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjM5MjY2MzA="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
