categories = "launched"
description = """
Bodenrichtwerte im Zeitverlauf - gefunden im FIS-Broker. Was sind Bodenrichtwerte? Laut Wikipedia
 ist “der Bodenrichtwert im deutschen Städtebaurecht ein 
durchschnittlicher Lagewert, ermittelt aus den Kaufpreisen von 
Grundstücken unter Berücksichtigung ihres Entwicklungszustandes bezogen 
auf den Quadratmeter Land.” Es geht also um den Wert von Grundstücken."""
link_url = "hanshans.ursa.uberspace.de/bodenrichtwerte/bodenrichtwerte.h2"
name = "Bodenrichtwerte im Zeitverlauf"
organization_name = "OK Lab Berlin"
