categories = "launched"
code_url = "https://github.com/BuergerbautStadt"
description = """
Finde mit Bürger Baut Stadt geplante Bauvorhaben in deiner Stadt! Auf 
einer Karte kannst du einsehen, wo gerade Bebauungspläne ausliegen und 
erfahren, wie Du dich mit deinen Ideen beteiligen kannst."""
link_url = "http://buergerbautstadt.de/"
name = "Buerger baut Stadt"
organization_name = "OK Lab Berlin"
type = "Community Plattform"
