categories = "launched, map"
description = """
Ernte-teilen.org bietet eine Plattform, die Landwirte und 
Verbraucherinnen, die sich an Solidarischer Landwirtschaft beteiligen 
möchten, zusammenfinden lässt."""
link_url = "https://ernte-teilen.org/"
name = "Ernte teilen"
organization_name = "OK Lab Berlin"
type = "Community Plattform"
