categories = "launched"
description = "Bürger können ihre Straßen vermessen und die Frage nach der Gerechtigkeit im Verkehr quadratmeter-scharf diskutieren."
link_url = "http://clevere-staedte.de/flaechen-gerechtigkeits-report-online"
name = "Flächengerechtigkeits-Tool"
organization_name = "OK Lab Berlin"
