categories = "launched, map"
code_url = "https://bitbucket.org/tbsprs/umweltzone"
description = """
Umweltzone ist eine Android App, die
 die Lage der Umweltzonen verschiedener Städte in Deutschland anzeigt. 
Datengrundlage sind digitale Veröffentlichungen von Behörden, 
OpenStreetMap oder manuell georeferenzierte PDFs.

Wer Lust hat einzusteigen, meldet sich bei mir - es gibt noch viele 
Ideen, wie man die App verbessern kann. Eine Roadmap muss ich noch 
schreiben - es gibt aber ein gut gefülltes Trello-Board. Der Quellcode 
ist natürlich frei zugänglich"""
link_url = "https://play.google.com/store/apps/details?id=de.avpptr.umweltzone"
name = "Umweltzone Android App"
organization_name = "OK Lab Berlin"
type = "Mobile App"
