code_url = "https://github.com/g0v/encoding-mashup-server"
description = "A system to help users find the correct Unicode or the CNS 11643 encoding for Han characters found as pictures (due to the limitation of Big-5) in many dictionaries published by the Ministry of Education (Taiwan)"
git_url = "git://github.com/g0v/encoding-mashup-server.git"
name = "encoding-mashup-server"
organization_name = "g0v.tw"

[github]
archived = false
created_at = "2013-02-09T07:08:40Z"
default_branch = "new-server"
description = "A system to help users find the correct Unicode or the CNS 11643 encoding for Han characters found as pictures (due to the limitation of Big-5) in many dictionaries published by the Ministry of Education (Taiwan)"
disabled = false
fork = false
forks_within = 0
full_name = "g0v/encoding-mashup-server"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 8_107_199
language = "JavaScript"
name = "encoding-mashup-server"
node_id = "MDEwOlJlcG9zaXRvcnk4MTA3MTk5"
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.license]
  key = "other"
  name = "Other"
  node_id = "MDc6TGljZW5zZTA="
  spdx_id = "NOASSERTION"

  [github.owner]
  gravatar_id = ""
  id = 2_668_086
  login = "g0v"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjI2NjgwODY="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
