code_url = "https://github.com/CivicTechTO/budgetcommons-dev-frontend"
description = "The mandate is to support informed debate about the Toronto budget by making the budget (information and process) more accessible to the public. Fulfillment is through creation of a website portal."
github = false
link_url = "http://civictech.ca/projects/#torontobudgetproject"
name = "Toronto Budget Project"
organization_name = "Civic Tech Toronto"
status = "alpha"
topics = [ "budget", "democracy", "opendata" ]

[projects_list_extra]
lead_github = "HenrikBechmann"
lead_slack = "henrik"
lead_twitter = "HenrikBechmann"
