description = "Das Digital Welcome/Refugee Lab Hamburg ist ein neues Projekt der Open Knowledge Foundation. In 4 Labs wird gezielt der Kontakt zu Organisationen hergestellt um die Zusammenarbeit zwischen technisch versierten Communitys, Ehrenamtlichen im Bereich der Flüchtlingshilfe, Geflüchteten sowie öffentlichen Verwaltungen zu verstetigen und auszubauen."
link_url = "http://codefor.de/digitalrefugeelabs/"
name = "Digital Welcome Lab"
organization_name = "Code for Hamburg"
