description = "Zeitziel: Herbst 2016. Mein Weg ins Hochschulsystem. Wie kommt man in das Hochschulsystem im föderalen, hochschulverwaltungstechnischen Kontext? Ziel ist ein Informationszugangssystem zu schaffen was Bewerbern wirklich hilft."
name = "Hack the study system!"
organization_name = "Code for Hamburg"
