code_url = "https://github.com/codeforhamburg/offenerhaushalt.de-hamburg"
description = "Visualisierung des Haushalts der Freien und Hansestadt Hamburg nach dem Vorbild vom Open Knowledge Foundation DE Projekt offenerhaushalt.de"
github = false
link_url = "http://offenerhaushalt.de/haushalt/bund/"
name = "Offenerhaushalt Hamburg"
organization_name = "Code for Hamburg"
