description = 'Wie komme ich durch Hamburg ohne an einer Spielhalle vorbei zu kommen? Normalerweise keine allt채gliche Frage, f체r einen (ehemaligen) Spiels체chtigen durchaus! Und: Wo sind eigentlich alle "Gl체cksspiel-Buden", Casinos, Zockerhallen, etc.? Alle auf St. Pauli oder auch in Wohngebieten, Gewerbegebieten, etc.?'
link_url = "https://ubilabs.cartodb.com/viz/09726236-e9ca-11e5-9a6b-0e98b61680bf/embed_map"
name = "Spielsucht-Karte Hamburg"
organization_name = "Code for Hamburg"
