code_url = "http://beta.wikidelphia.org/After-school_Programs"
description = "With summer school eliminated, provide parents and students access to a comprehensive list of credit recovery and extracurricular options based on location."
link_url = "http://beta.wikidelphia.org/After-school_Programs"
name = "After_School_Wiki"
organization_name = "Code for Philly"
status = "Hibernating"
topics = [ "Education" ]

[projects_list_extra]
title = "After-school Wiki"
