description = "The aim of this project is to create a bicyclist detector. Given a video, the algorithm should detect the bicyclist within each frame of the video. Hopefully, this can be used to get bicyclist counts."
name = "bicyclist_detector"
organization_name = "Code for Philly"
status = "Prototyping"
topics = [ "Biking", "Computer Vision", "Machine Learning" ]

[projects_list_extra]
title = "Bicyclist Detector"
