code_url = "http://github.com/pnchappy92"
description = "Download it here https://play.google.com/store/apps/details?id=com.peterchappy.bikesharephilly&hl=en"
link_url = "https://play.google.com/store/apps/details?id=com.peterchappy.bikesharephilly&hl=en"
name = "bike_share_philly_android"
organization_name = "Code for Philly"
status = "Maintaining"
topics = [ "bike sharing", "Biking", "Mapping", "Mobile" ]

[projects_list_extra]
title = "Bike Share Philly Android"
