code_url = "http://communitymagic.org/wp-admin"
description = 'We are building a network of community advocates in neighborhoods, community centers and churches. This process will provide personal, one-on-one "real needs" counseling and "match making" of needs to resources to help people find the social supports and material connections needed to make everyday living more productive and less difficult.'
link_url = "http://communitymagic.org"
name = "Community_Magic"
organization_name = "Code for Philly"
status = "Commenting"
topics = [ "CivicEngagement", "Communities" ]

[projects_list_extra]
title = "Community Magic"
