description = "A collection of documents, tools and articles on how to create and manage single purpose servers."
name = "DevOps_for_Normals"
organization_name = "Code for Philly"
status = "Commenting"
topics = [ "DevOps" ]

[projects_list_extra]
title = "DevOps for Normals"
