code_url = "https://github.com/PrideNJellyfish/Happy2Help/blob/master/README.md"
description = "https://github.com/PrideNJellyfish/Happy2Help"
link_url = "https://www.eventbrite.com/e/save-the-world-helpathon-registration-78924512341"
name = "facilitating_thriving"
organization_name = "Code for Philly"
status = "Bootstrapping"
topics = [
  "CivicEngagement",
  "Data",
  "Democracy",
  "Economic Inequality",
  "Education",
  "local economy",
  "Open Data",
  "Open Source",
  "sustainability"
]

[projects_list_extra]
chat_channel = "facilitating-thriving"
title = "Facilitating Thriving"
