description = "An web app designed at the Apps for Philly Health hackathon in May 2015.  The goal of the app is assist a user in finding the best options available when facing a mental health crisis."
link_url = "http://mental-health.poplar.phl.io/index.php"
name = "friendtervention"
organization_name = "Code for Philly"
status = "Prototyping"
topics = [ "Health" ]

[projects_list_extra]
title = "Friendtervention"
