description = "PROJECT ON HOLD"
link_url = "https://uno.nhu313.com/"
name = "interpreter_training"
organization_name = "Code for Philly"
status = "Commenting"
topics = [
  "Education",
  "foreign language",
  "Language",
  "Language Access"
]

[projects_list_extra]
title = "PROJECT ON HOLD - Interpreter Training"
