description = "A LocalWiki for Philadelphia."
link_url = "http://localwiki.org/philadelphia/"
name = "localwiki"
organization_name = "Code for Philly"
status = "Maintaining"
topics = [ "Education", "Knowledge" ]

[projects_list_extra]
title = "LocalWiki"
