description = "Perfect-Dispatch-Fire"
name = "perfect_dispatch_fire"
organization_name = "Code for Philly"
status = "Commenting"
topics = [ "Mapping", "Pred", "services" ]

[projects_list_extra]
chat_channel = "perfect-dispatch-fire"
title = "Perfect Dispatch Fire"
