description = "PROBLEM: Inability to perform simple home maintenance or repairs makes it harder for seniors to age in place."
name = "philly_elder_helpers"
organization_name = "Code for Philly"
status = "Bootstrapping"

[projects_list_extra]
chat_channel = "phillyelderhelpers"
title = "Philly Elder Helpers"
