description = "As an unfunded project, it can use all the support it can get. Looking for collaboration to help increase its adoption, ideas to spread awareness, and tie-ins with other food access efforts."
link_url = "https://www.phillyfoodfinder.org"
name = "philly_food_finder"
organization_name = "Code for Philly"
status = "Maintaining"
topics = [
  "covid-19",
  "fighting poverty",
  "Food",
  "Food and Beverage",
  "Food Insecurity",
  "Poverty"
]

[projects_list_extra]
title = "Philly Food Finder"
