description = "Philadelphia Bail Fund (PBF) is a revolving fund that posts bail for people who are indigent and cannot afford bail. Our goal is to keep families and communities together and vigorously advocate for the end to cash bail in Philadelphia."
link_url = "https://www.phillybailfund.org/"
name = "philadelphia_bail_fund_interactive_data_portal"
organization_name = "Code for Philly"
status = "Bootstrapping"
topics = [
  "Coding projects",
  "data analysis",
  "data management",
  "Data Science",
  "Injustice",
  "Social Justice",
  "Social projects",
  "Transformative-Justice"
]

[projects_list_extra]
chat_channel = "philadelphia-bail-fund"
title = "Philadelphia Bail Fund Interactive Data Portal"
