code_url = "http://git.kclough.me/kclough/nodeelectionscraper"
description = "Tim Wisniewski wrote an election scraper with Kimono and a html page to display live election results scraped from http://phillyelectionresults.com/."
link_url = "http://whowonphilly.com"
name = "philly_election_live_results"
organization_name = "Code for Philly"
status = "Maintaining"
topics = [ "2015", "Elections", "nextmayorphl", "Open Data", "Politics" ]

[projects_list_extra]
title = "Who Won Philly"
