description = "Philadelphia Auto and Parole is a re-entry program to provide formerly incarcerated individuals and youth transitioning back into society an opportunity to earn a living wage through courses in automotive repair. **In order to financially support the classes, Philly Auto and Parole functions as both a repair shop and an educational program.**"
link_url = "https://philadelphiaautoandparole.org"
name = "philly_auto_and_parole"
organization_name = "Code for Philly"
status = "Commenting"
topics = [ "Cars", "Criminal Justice Reform" ]

[projects_list_extra]
chat_channel = "phillyautoandparole"
title = "Philly Auto and Parole"
