description = "Research, and common sense, indicate that early childhood is a pivotal time for creating the foundation for success in future learning. Did you know that only 7% of early childhood education centers in the city are considered \"high quality\" by the state's Keystone STARS rating system? And, consequentially, that only a small fraction of Philadelphia's children have access to an quality early childhood education setting?"
name = "Philadelphia_for_Early_Childhood_Education_Mapping_Project"
organization_name = "Code for Philly"
status = "Hibernating"

[projects_list_extra]
title = "Philadelphia for Early Childhood Education Mapping Project"
