code_url = "https://github.com/davewalk/phl-crime-mapper"
description = "PHL Crime Mapper lets you see the Part I (violent and property) crimes that have occurred in an area of Philadelphia that you care about."
github = false
link_url = "http://www.phlcrimemapper.com"
name = "PHL_Crime_Mapper"
organization_name = "Code for Philly"
status = "Maintaining"
topics = [ "Crime", "GIS", "Maps" ]

[projects_list_extra]
title = "PHL Crime Mapper"
