code_url = "https://sillyutility.net/"
description = "Compare utility bills with neighbors. https://sillyutility.net/"
link_url = "https://sillyutility.net/"
name = "silly_utility"
organization_name = "Code for Philly"
status = "Testing"
topics = [
  "Anti-corporate",
  "Data",
  "Inequality Anti-corporation",
  "local economy",
  "Utilities"
]

[projects_list_extra]
chat_channel = "sillyutility"
title = "Silly Utility"
