description = "I want to create a social hub for programmers to do daily challenges. The objective of this project is to create a website where users can post programming questions and users are allowed to challenge them by answer the programming question. In the end establishing a community of programming elites. Does anyone want to hop onboard?"
name = "social_hub_for_programmers"
organization_name = "Code for Philly"
status = "Commenting"
topics = [ "Agile Practices", "Coding", "Education" ]

[projects_list_extra]
title = "Social Hub For Programmers"
