description = "A decommissioned computer hardware exchange. Linking corporations with non-profits and local schools."
link_url = "http://technologydoes.org"
name = "technology_does"
organization_name = "Code for Philly"
status = "Commenting"

[projects_list_extra]
title = "Technology Does"
