code_url = "https://github.com/cityballots"
description = "I want a simple way for people to know who they are voting for."
name = "text2vote"
organization_name = "Code for Philly"
status = "Bootstrapping"
topics = [ "Elections" ]

[projects_list_extra]
chat_channel = "cityballots"
title = "CityBallots"
