description = "Just trying to produce some simple maps that overlay demographic data with maps of transportation committee members to support a legislative campaign. Looking for data transformation help!"
link_url = "https://dafeder.cartodb.com/viz/d044ded2-a94a-11e4-a2d7-0e0c41326911/public_map"
name = "transportation_committee_maps"
organization_name = "Code for Philly"
status = "Prototyping"
topics = [ "Transportation" ]

[projects_list_extra]
title = "Transportation Committee Maps"
