description = "We're working with [The Reentry Project](https://thereentryproject.org/) to create an online, multimedia experience that will challenge people's perception of what someone with a criminal record looks like. This is currently planned through three pieces:"
name = "un-incarcerated_-_a_multimedia_documentary_project_on_incarceration_and_reentry"
organization_name = "Code for Philly"
status = "Commenting"
topics = [
  "Criminal Justice Reform",
  "Documentary",
  "Film",
  "Journalism",
  "Multimedia",
  "Photography",
  "Returning-Citizens"
]

[projects_list_extra]
chat_channel = "unincarcerated"
title = "(Un)Incarcerated - A Multimedia Documentary Project on Incarceration and Reentry"
