code_url = "https://github.com/ppierdo/Voter-Turnout-Maps.git"
description = "This project maps the voter turnout in the November 2014 general election.  It looks at the percentage of registered voters who voted in each census block group; it also examines demographic characteristics reported by the American Community Survey to try to find correlations between demographics and turnout."
github = false
link_url = "https://github.com/ppierdo/Voter-Turnout-Maps/tree/gh-pages"
name = "voter_turnout_in_the_40th_ward"
organization_name = "Code for Philly"
status = "Maintaining"
topics = [ "voter registration", "Voting" ]

[projects_list_extra]
title = "Voter Turnout in the 2014 General Election"
