link_url = "https://public.tableau.com/profile/zach3504#!/vizhome/WillistownRecyclingLookup/Search?publish=yes"
name = "willistown_township_recycling_resource_lookup"
organization_name = "Code for Philly"
status = "Testing"

[projects_list_extra]
title = "Willistown Township Recycling Resource Lookup"
