description = "A civic project to assist tourists and locals to quickly navigate to quality food experiences."
name = "you_need_to_eat_this"
organization_name = "Code for Philly"
status = "Commenting"
topics = [ "Tourism" ]

[projects_list_extra]
title = "You Need to Eat This"
