code_url = "https://github.com/Code4PuertoRico/suministrospr"
description = "Suministros Puerto Rico - Entérate, Ayuda, Informa"
git_url = "git://github.com/Code4PuertoRico/suministrospr.git"
link_url = "https://suministrospr.com"
name = "suministrospr"
organization_name = "Code4PuertoRico"
topics = [
  "civic-tech",
  "code4pr",
  "disaster-response",
  "django",
  "python",
  "suministros-puerto-rico"
]

[github]
archived = false
created_at = "2020-01-13T21:18:07Z"
default_branch = "master"
description = "Suministros Puerto Rico - Entérate, Ayuda, Informa"
disabled = false
fork = false
forks_within = 100
full_name = "Code4PuertoRico/suministrospr"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = "https://suministrospr.com"
id = 233_695_497
language = "Python"
name = "suministrospr"
node_id = "MDEwOlJlcG9zaXRvcnkyMzM2OTU0OTc="
open_issues_within = 0
private = false
pushed_within = "year"
stargazers_within = 100
topics = [
  "civic-tech",
  "code4pr",
  "disaster-response",
  "django",
  "python",
  "suministros-puerto-rico"
]
updated_within = "year"
watchers_within = 100

  [github.license]
  key = "apache-2.0"
  name = "Apache License 2.0"
  node_id = "MDc6TGljZW5zZTI="
  spdx_id = "Apache-2.0"

  [github.owner]
  gravatar_id = ""
  id = 6_626_422
  login = "Code4PuertoRico"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2MjY0MjI="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
