code_url = "https://github.com/Code4PuertoRico/website"
description = "The new and improved website for Code for Puerto Rico."
git_url = "git://github.com/Code4PuertoRico/website.git"
name = "website"
organization_name = "Code4PuertoRico"

[github]
archived = false
created_at = "2020-01-31T14:34:18Z"
default_branch = "master"
description = "The new and improved website for Code for Puerto Rico."
disabled = false
fork = true
forks_within = 0
full_name = "Code4PuertoRico/website"
has_downloads = true
has_issues = false
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 237_447_649
language = { }
name = "website"
node_id = "MDEwOlJlcG9zaXRvcnkyMzc0NDc2NDk="
open_issues_within = 0
private = false
pushed_within = "year"
stargazers_within = 0
topics = [ ]
updated_within = "year"
watchers_within = 0

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_626_422
  login = "Code4PuertoRico"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2MjY0MjI="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
