code_url = "https://github.com/codeforsanjose/awesome-civic"
description = "A list of resources for awesome civic software tools, libraries, and applications."
git_url = "git://github.com/codeforsanjose/awesome-civic.git"
name = "awesome-civic"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2016-03-26T00:33:36Z"
default_branch = "master"
description = "A list of resources for awesome civic software tools, libraries, and applications."
disabled = false
fork = true
forks_within = 0
full_name = "codeforsanjose/awesome-civic"
has_downloads = true
has_issues = false
has_pages = false
has_projects = true
has_wiki = false
homepage = ""
id = 54_755_115
language = { }
name = "awesome-civic"
node_id = "MDEwOlJlcG9zaXRvcnk1NDc1NTExNQ=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.license]
  key = "cc0-1.0"
  name = "Creative Commons Zero v1.0 Universal"
  node_id = "MDc6TGljZW5zZTY="
  spdx_id = "CC0-1.0"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
