code_url = "https://github.com/codeforsanjose/beggar"
description = "Automatically ask for a PR review"
git_url = "git://github.com/codeforsanjose/beggar.git"
name = "beggar"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2015-12-19T23:12:29Z"
default_branch = "master"
description = "Automatically ask for a PR review"
disabled = false
fork = true
forks_within = 0
full_name = "codeforsanjose/beggar"
has_downloads = true
has_issues = false
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 48_300_373
language = "Ruby"
name = "beggar"
node_id = "MDEwOlJlcG9zaXRvcnk0ODMwMDM3Mw=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
