code_url = "https://github.com/codeforsanjose/BLiC-Java-UI"
git_url = "git://github.com/codeforsanjose/BLiC-Java-UI.git"
name = "BLiC-Java-UI"
organization_name = "Code for San Jose"
topics = [ "utilities" ]

[github]
archived = false
created_at = "2016-07-15T03:07:22Z"
default_branch = "master"
description = { }
disabled = false
fork = false
forks_within = 10
full_name = "codeforsanjose/BLiC-Java-UI"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 63_387_495
language = "CSS"
name = "BLiC-Java-UI"
node_id = "MDEwOlJlcG9zaXRvcnk2MzM4NzQ5NQ=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ "utilities" ]
updated_within = "over_a_year"
watchers_within = 0

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
