code_url = "https://github.com/codeforsanjose/blog_archive"
description = "Code for San José's Blog content"
git_url = "git://github.com/codeforsanjose/blog_archive.git"
name = "blog_archive"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2017-04-14T03:14:45Z"
default_branch = "master"
description = "Code for San José's Blog content"
disabled = false
fork = false
forks_within = 0
full_name = "codeforsanjose/blog_archive"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = true
homepage = ""
id = 88_228_302
language = "CSS"
license = { }
name = "blog_archive"
node_id = "MDEwOlJlcG9zaXRvcnk4ODIyODMwMg=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
