code_url = "https://github.com/codeforsanjose/bot311"
description = "Extensible Open311 chatbot to report issues in your community"
git_url = "git://github.com/codeforsanjose/bot311.git"
name = "bot311"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2016-12-02T03:18:06Z"
default_branch = "master"
description = "Extensible Open311 chatbot to report issues in your community"
disabled = false
fork = false
forks_within = 10
full_name = "codeforsanjose/bot311"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 75_356_325
language = "JavaScript"
name = "bot311"
node_id = "MDEwOlJlcG9zaXRvcnk3NTM1NjMyNQ=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.license]
  key = "agpl-3.0"
  name = "GNU Affero General Public License v3.0"
  node_id = "MDc6TGljZW5zZTE="
  spdx_id = "AGPL-3.0"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
