code_url = "https://github.com/codeforsanjose/brigadehub"
description = "Focus on what your community needs, not your website :computer:"
git_url = "git://github.com/codeforsanjose/brigadehub.git"
link_url = "https://brigadehub.github.io/"
name = "brigadehub"
organization_name = "Code for San Jose"
topics = [ "inactive", "website" ]

[github]
archived = false
created_at = "2016-12-16T02:08:11Z"
default_branch = "develop"
description = "Focus on what your community needs, not your website :computer:"
disabled = false
fork = true
forks_within = 10
full_name = "codeforsanjose/brigadehub"
has_downloads = true
has_issues = false
has_pages = false
has_projects = true
has_wiki = true
homepage = "https://brigadehub.github.io/"
id = 76_612_730
language = "JavaScript"
license = { }
name = "brigadehub"
node_id = "MDEwOlJlcG9zaXRvcnk3NjYxMjczMA=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ "inactive", "website" ]
updated_within = "over_a_year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
