code_url = "https://github.com/codeforsanjose/broken-link-reporter"
git_url = "git://github.com/codeforsanjose/broken-link-reporter.git"
name = "broken-link-reporter"
organization_name = "Code for San Jose"
topics = [ "python", "utilities" ]

[github]
archived = false
created_at = "2016-06-10T02:37:42Z"
default_branch = "master"
description = { }
disabled = false
fork = false
forks_within = 10
full_name = "codeforsanjose/broken-link-reporter"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 60_820_076
language = "Python"
name = "broken-link-reporter"
node_id = "MDEwOlJlcG9zaXRvcnk2MDgyMDA3Ng=="
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ "python", "utilities" ]
updated_within = "over_a_year"
watchers_within = 0

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
