code_url = "https://github.com/codeforsanjose/C4SJwebsite-laddr"
git_url = "git://github.com/codeforsanjose/C4SJwebsite-laddr.git"
name = "C4SJwebsite-laddr"
organization_name = "Code for San Jose"
topics = [ "inactive", "website" ]

[github]
archived = false
created_at = "2015-10-24T21:45:45Z"
default_branch = "development"
description = { }
disabled = false
fork = true
forks_within = 0
full_name = "codeforsanjose/C4SJwebsite-laddr"
has_downloads = true
has_issues = false
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 44_886_202
language = "JavaScript"
name = "C4SJwebsite-laddr"
node_id = "MDEwOlJlcG9zaXRvcnk0NDg4NjIwMg=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ "inactive", "website" ]
updated_within = "over_a_year"
watchers_within = 10

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
