code_url = "https://github.com/codeforsanjose/calidrought"
description = "An API for serving up data on the California drought."
git_url = "git://github.com/codeforsanjose/calidrought.git"
name = "calidrought"
organization_name = "Code for San Jose"
topics = [
  "api",
  "codeforamerica",
  "codeforsanjose",
  "drought",
  "elixir",
  "open-data",
  "phoenix"
]

[github]
archived = false
created_at = "2017-01-30T12:53:10Z"
default_branch = "master"
description = "An API for serving up data on the California drought."
disabled = false
fork = false
forks_within = 0
full_name = "codeforsanjose/calidrought"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 80_421_284
language = "JavaScript"
name = "calidrought"
node_id = "MDEwOlJlcG9zaXRvcnk4MDQyMTI4NA=="
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [
  "api",
  "codeforamerica",
  "codeforsanjose",
  "drought",
  "elixir",
  "open-data",
  "phoenix"
]
updated_within = "over_a_year"
watchers_within = 10

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
