code_url = "https://github.com/codeforsanjose/census-viewers"
git_url = "git://github.com/codeforsanjose/census-viewers.git"
name = "census-viewers"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2016-09-09T01:38:14Z"
default_branch = "master"
description = { }
disabled = false
fork = false
forks_within = 0
full_name = "codeforsanjose/census-viewers"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 67_754_758
language = { }
name = "census-viewers"
node_id = "MDEwOlJlcG9zaXRvcnk2Nzc1NDc1OA=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
