code_url = "https://github.com/codeforsanjose/citysourced-api-simulator"
description = "Simulates the CitySourced API backend."
git_url = "git://github.com/codeforsanjose/citysourced-api-simulator.git"
name = "citysourced-api-simulator"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2015-11-19T19:50:31Z"
default_branch = "master"
description = "Simulates the CitySourced API backend."
disabled = false
fork = false
forks_within = 10
full_name = "codeforsanjose/citysourced-api-simulator"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 46_516_457
language = "Go"
name = "citysourced-api-simulator"
node_id = "MDEwOlJlcG9zaXRvcnk0NjUxNjQ1Nw=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
