code_url = "https://github.com/codeforsanjose/codeforsanjose-backend"
description = "A prototype website for Code for San Jose."
git_url = "git://github.com/codeforsanjose/codeforsanjose-backend.git"
name = "codeforsanjose-backend"
organization_name = "Code for San Jose"
topics = [ "inactive", "website" ]

[github]
archived = false
created_at = "2015-11-13T15:16:56Z"
default_branch = "develop"
description = "A prototype website for Code for San Jose."
disabled = false
fork = false
forks_within = 10
full_name = "codeforsanjose/codeforsanjose-backend"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 46_129_278
language = "JavaScript"
license = { }
name = "codeforsanjose-backend"
node_id = "MDEwOlJlcG9zaXRvcnk0NjEyOTI3OA=="
open_issues_within = 100
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ "inactive", "website" ]
updated_within = "over_a_year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
