code_url = "https://github.com/codeforsanjose/codeforsanjose-frontend"
git_url = "git://github.com/codeforsanjose/codeforsanjose-frontend.git"
name = "codeforsanjose-frontend"
organization_name = "Code for San Jose"
topics = [ "inactive", "website" ]

[github]
archived = false
created_at = "2015-12-14T02:59:37Z"
default_branch = "master"
description = { }
disabled = false
fork = false
forks_within = 10
full_name = "codeforsanjose/codeforsanjose-frontend"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 47_948_798
language = "CSS"
name = "codeforsanjose-frontend"
node_id = "MDEwOlJlcG9zaXRvcnk0Nzk0ODc5OA=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ "inactive", "website" ]
updated_within = "over_a_year"
watchers_within = 0

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
