code_url = "https://github.com/codeforsanjose/crisisresponse"
description = "An internal tool to help the Seattle Police Department respond to the needs of people in crisis"
git_url = "git://github.com/codeforsanjose/crisisresponse.git"
name = "crisisresponse"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2016-12-15T02:54:17Z"
default_branch = "master"
description = "An internal tool to help the Seattle Police Department respond to the needs of people in crisis"
disabled = false
fork = true
forks_within = 0
full_name = "codeforsanjose/crisisresponse"
has_downloads = true
has_issues = false
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 76_518_118
language = "Ruby"
license = { }
name = "crisisresponse"
node_id = "MDEwOlJlcG9zaXRvcnk3NjUxODExOA=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
