code_url = "https://github.com/codeforsanjose/CSV-Validator"
git_url = "git://github.com/codeforsanjose/CSV-Validator.git"
name = "CSV-Validator"
organization_name = "Code for San Jose"
topics = [ "inactive" ]

[github]
archived = false
created_at = "2016-11-16T22:25:28Z"
default_branch = "master"
description = { }
disabled = false
fork = false
forks_within = 10
full_name = "codeforsanjose/CSV-Validator"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 73_966_794
language = "Python"
license = { }
name = "CSV-Validator"
node_id = "MDEwOlJlcG9zaXRvcnk3Mzk2Njc5NA=="
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ "inactive" ]
updated_within = "over_a_year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
