code_url = "https://github.com/codeforsanjose/CycleSafe"
description = "CycleSafe allows cyclists and pedestrians to map dangerous routes in their communities"
git_url = "git://github.com/codeforsanjose/CycleSafe.git"
link_url = "http://cyclesafe.us"
name = "CycleSafe"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2014-08-18T20:32:28Z"
default_branch = "master"
description = "CycleSafe allows cyclists and pedestrians to map dangerous routes in their communities"
disabled = false
fork = false
forks_within = 10
full_name = "codeforsanjose/CycleSafe"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = "http://cyclesafe.us"
id = 23_085_580
language = "Python"
name = "CycleSafe"
node_id = "MDEwOlJlcG9zaXRvcnkyMzA4NTU4MA=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
