code_url = "https://github.com/codeforsanjose/data-requests"
description = 'Use the "Issues" page to place inquiries about government datasets.'
git_url = "git://github.com/codeforsanjose/data-requests.git"
name = "data-requests"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2015-10-23T02:44:27Z"
default_branch = "master"
description = 'Use the "Issues" page to place inquiries about government datasets.'
disabled = false
fork = false
forks_within = 0
full_name = "codeforsanjose/data-requests"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 44_786_680
language = { }
license = { }
name = "data-requests"
node_id = "MDEwOlJlcG9zaXRvcnk0NDc4NjY4MA=="
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
