code_url = "https://github.com/codeforsanjose/Emotional-Flash"
description = "Flashcard game for children with Autism to help them recognize emotions"
git_url = "git://github.com/codeforsanjose/Emotional-Flash.git"
name = "Emotional-Flash"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2018-02-09T03:34:02Z"
default_branch = "master"
description = "Flashcard game for children with Autism to help them recognize emotions"
disabled = false
fork = false
forks_within = 10
full_name = "codeforsanjose/Emotional-Flash"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = true
homepage = ""
id = 120_852_010
language = "JavaScript"
license = { }
name = "Emotional-Flash"
node_id = "MDEwOlJlcG9zaXRvcnkxMjA4NTIwMTA="
open_issues_within = 100
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
