code_url = "https://github.com/codeforsanjose/GiveLightFoundation"
description = "Organization tool for registering volunteers and searching through volunteers"
git_url = "git://github.com/codeforsanjose/GiveLightFoundation.git"
name = "GiveLightFoundation"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2018-03-13T00:59:53Z"
default_branch = "master"
description = "Organization tool for registering volunteers and searching through volunteers"
disabled = false
fork = false
forks_within = 10
full_name = "codeforsanjose/GiveLightFoundation"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 124_971_204
language = "JavaScript"
license = { }
name = "GiveLightFoundation"
node_id = "MDEwOlJlcG9zaXRvcnkxMjQ5NzEyMDQ="
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
