code_url = "https://github.com/codeforsanjose/iD"
description = "The easy-to-use OpenStreetMap editor in JavaScript."
git_url = "git://github.com/codeforsanjose/iD.git"
link_url = "http://www.openstreetmap.org/edit?editor=id"
name = "iD"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2017-12-02T00:30:20Z"
default_branch = "master"
description = "The easy-to-use OpenStreetMap editor in JavaScript."
disabled = false
fork = true
forks_within = 0
full_name = "codeforsanjose/iD"
has_downloads = true
has_issues = false
has_pages = true
has_projects = true
has_wiki = true
homepage = "http://www.openstreetmap.org/edit?editor=id"
id = 112_799_807
language = "JavaScript"
name = "iD"
node_id = "MDEwOlJlcG9zaXRvcnkxMTI3OTk4MDc="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.license]
  key = "isc"
  name = "ISC License"
  node_id = "MDc6TGljZW5zZTEw"
  spdx_id = "ISC"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
