code_url = "https://github.com/codeforsanjose/ImmunizationSJ"
description = "An app that finds immunization information for schools."
git_url = "git://github.com/codeforsanjose/ImmunizationSJ.git"
name = "ImmunizationSJ"
organization_name = "Code for San Jose"
topics = [ "inactive" ]

[github]
archived = false
created_at = "2015-01-31T19:12:18Z"
default_branch = "master"
description = "An app that finds immunization information for schools."
disabled = false
fork = false
forks_within = 10
full_name = "codeforsanjose/ImmunizationSJ"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 30_122_940
language = "Python"
name = "ImmunizationSJ"
node_id = "MDEwOlJlcG9zaXRvcnkzMDEyMjk0MA=="
open_issues_within = 100
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ "inactive" ]
updated_within = "over_a_year"
watchers_within = 10

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
