code_url = "https://github.com/codeforsanjose/inventory-control"
description = "A system that receives,stores, and manages computer parts, components and finished goods."
git_url = "git://github.com/codeforsanjose/inventory-control.git"
name = "inventory-control"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2015-07-24T10:07:34Z"
default_branch = "master"
description = "A system that receives,stores, and manages computer parts, components and finished goods."
disabled = false
fork = false
forks_within = 10
full_name = "codeforsanjose/inventory-control"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 39_625_318
language = "Python"
name = "inventory-control"
node_id = "MDEwOlJlcG9zaXRvcnkzOTYyNTMxOA=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "year"
watchers_within = 10

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
