code_url = "https://github.com/codeforsanjose/MobilityMapApi"
description = "The Mission Critical Mobility Maps Api"
git_url = "git://github.com/codeforsanjose/MobilityMapApi.git"
name = "MobilityMapApi"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2015-08-03T01:11:55Z"
default_branch = "master"
description = "The Mission Critical Mobility Maps Api"
disabled = false
fork = false
forks_within = 0
full_name = "codeforsanjose/MobilityMapApi"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 40_098_580
language = "Python"
name = "MobilityMapApi"
node_id = "MDEwOlJlcG9zaXRvcnk0MDA5ODU4MA=="
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.license]
  key = "gpl-3.0"
  name = "GNU General Public License v3.0"
  node_id = "MDc6TGljZW5zZTk="
  spdx_id = "GPL-3.0"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
