code_url = "https://github.com/codeforsanjose/MobilityMapChef"
description = "A chef script to deploy Mobility Maps"
git_url = "git://github.com/codeforsanjose/MobilityMapChef.git"
name = "MobilityMapChef"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2015-08-03T04:01:03Z"
default_branch = "master"
description = "A chef script to deploy Mobility Maps"
disabled = false
fork = false
forks_within = 0
full_name = "codeforsanjose/MobilityMapChef"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 40_104_274
language = "Ruby"
name = "MobilityMapChef"
node_id = "MDEwOlJlcG9zaXRvcnk0MDEwNDI3NA=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
