code_url = "https://github.com/codeforsanjose/neighborhood-association"
description = "A webpage for citizens of San Jose to discover their friendly local Neighborhood Associations"
git_url = "git://github.com/codeforsanjose/neighborhood-association.git"
name = "neighborhood-association"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2016-10-14T03:02:39Z"
default_branch = "master"
description = "A webpage for citizens of San Jose to discover their friendly local Neighborhood Associations"
disabled = false
fork = false
forks_within = 0
full_name = "codeforsanjose/neighborhood-association"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = true
homepage = { }
id = 70_868_914
language = "JavaScript"
license = { }
name = "neighborhood-association"
node_id = "MDEwOlJlcG9zaXRvcnk3MDg2ODkxNA=="
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
