code_url = "https://github.com/codeforsanjose/odata-reader"
description = "Read Odata from San Jose API and display it for consumption."
git_url = "git://github.com/codeforsanjose/odata-reader.git"
name = "odata-reader"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2016-09-23T03:44:08Z"
default_branch = "master"
description = "Read Odata from San Jose API and display it for consumption."
disabled = false
fork = false
forks_within = 0
full_name = "codeforsanjose/odata-reader"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = true
homepage = { }
id = 68_986_321
language = "HTML"
license = { }
name = "odata-reader"
node_id = "MDEwOlJlcG9zaXRvcnk2ODk4NjMyMQ=="
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
