code_url = "https://github.com/codeforsanjose/OpenData"
git_url = "git://github.com/codeforsanjose/OpenData.git"
name = "OpenData"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2018-06-11T14:56:39Z"
default_branch = "master"
description = { }
disabled = false
fork = true
forks_within = 0
full_name = "codeforsanjose/OpenData"
has_downloads = true
has_issues = false
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 136_941_509
language = { }
license = { }
name = "OpenData"
node_id = "MDEwOlJlcG9zaXRvcnkxMzY5NDE1MDk="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
