code_url = "https://github.com/codeforsanjose/open311-server-implementation"
git_url = "git://github.com/codeforsanjose/open311-server-implementation.git"
name = "open311-server-implementation"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2015-08-28T02:55:15Z"
default_branch = "master"
description = { }
disabled = false
fork = false
forks_within = 0
full_name = "codeforsanjose/open311-server-implementation"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 41_523_558
language = "Ruby"
license = { }
name = "open311-server-implementation"
node_id = "MDEwOlJlcG9zaXRvcnk0MTUyMzU1OA=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
