code_url = "https://github.com/codeforsanjose/open311-gateway"
description = "311 Gateway coded in Go."
git_url = "git://github.com/codeforsanjose/open311-gateway.git"
name = "open311-gateway"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2015-12-11T21:21:10Z"
default_branch = "master"
description = "311 Gateway coded in Go."
disabled = false
fork = false
forks_within = 10
full_name = "codeforsanjose/open311-gateway"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 47_851_627
language = "Go"
name = "open311-gateway"
node_id = "MDEwOlJlcG9zaXRvcnk0Nzg1MTYyNw=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "year"
watchers_within = 10

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
