code_url = "https://github.com/codeforsanjose/OpenDSJ"
description = "Inform voters about San José, California local candidates and campaign finance. This is for 2014 election. For 2018+ go to github.com/codeforsanjose/OpenDSJ-2018"
git_url = "git://github.com/codeforsanjose/OpenDSJ.git"
link_url = "http://www.codeforsanjose.com/opendisclosure/"
name = "OpenDSJ"
organization_name = "Code for San Jose"
topics = [
  "campaign-finance-data",
  "dashboard",
  "datavisualization",
  "election",
  "map",
  "sanjose",
  "transparency"
]

[github]
archived = false
created_at = "2014-06-01T03:48:33Z"
default_branch = "3vivekb-master"
description = "Inform voters about San José, California local candidates and campaign finance. This is for 2014 election. For 2018+ go to github.com/codeforsanjose/OpenDSJ-2018"
disabled = false
fork = false
forks_within = 10
full_name = "codeforsanjose/OpenDSJ"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = true
homepage = "http://www.codeforsanjose.com/opendisclosure/"
id = 20_370_372
language = "R"
name = "OpenDSJ"
node_id = "MDEwOlJlcG9zaXRvcnkyMDM3MDM3Mg=="
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [
  "campaign-finance-data",
  "dashboard",
  "datavisualization",
  "election",
  "map",
  "sanjose",
  "transparency"
]
updated_within = "over_a_year"
watchers_within = 10

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
