code_url = "https://github.com/codeforsanjose/open311-plan-for-san-jose"
description = "An App and Infrastructure to report issues within San Jose"
git_url = "git://github.com/codeforsanjose/open311-plan-for-san-jose.git"
name = "open311-plan-for-san-jose"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2015-08-02T15:06:23Z"
default_branch = "master"
description = "An App and Infrastructure to report issues within San Jose"
disabled = false
fork = false
forks_within = 10
full_name = "codeforsanjose/open311-plan-for-san-jose"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 40_083_037
language = "R"
name = "open311-plan-for-san-jose"
node_id = "MDEwOlJlcG9zaXRvcnk0MDA4MzAzNw=="
open_issues_within = 100
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
