code_url = "https://github.com/codeforsanjose/OpenDataPledgeWebsite"
description = "Taking candidate names and city name out of the html. "
git_url = "git://github.com/codeforsanjose/OpenDataPledgeWebsite.git"
name = "OpenDataPledgeWebsite"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2014-08-15T03:29:15Z"
default_branch = "master"
description = "Taking candidate names and city name out of the html. "
disabled = false
fork = false
forks_within = 10
full_name = "codeforsanjose/OpenDataPledgeWebsite"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 22_977_370
language = { }
license = { }
name = "OpenDataPledgeWebsite"
node_id = "MDEwOlJlcG9zaXRvcnkyMjk3NzM3MA=="
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
