code_url = "https://github.com/codeforsanjose/OpenDSJv2"
description = "Second Generation of the Open Disclosure for San Jose project. "
git_url = "git://github.com/codeforsanjose/OpenDSJv2.git"
name = "OpenDSJv2"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2014-09-02T06:02:27Z"
default_branch = "master"
description = "Second Generation of the Open Disclosure for San Jose project. "
disabled = false
fork = true
forks_within = 10
full_name = "codeforsanjose/OpenDSJv2"
has_downloads = true
has_issues = false
has_pages = true
has_projects = true
has_wiki = true
homepage = { }
id = 23_567_004
language = "JavaScript"
name = "OpenDSJv2"
node_id = "MDEwOlJlcG9zaXRvcnkyMzU2NzAwNA=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
