code_url = "https://github.com/codeforsanjose/OpenDSJ-2018"
description = "Inform voters about 2018 San José, California and local candidates' campaign finance. "
git_url = "git://github.com/codeforsanjose/OpenDSJ-2018.git"
name = "OpenDSJ-2018"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2018-03-29T04:52:55Z"
default_branch = "master"
description = "Inform voters about 2018 San José, California and local candidates' campaign finance. "
disabled = false
fork = false
forks_within = 10
full_name = "codeforsanjose/OpenDSJ-2018"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 127_238_335
language = "Jupyter Notebook"
name = "OpenDSJ-2018"
node_id = "MDEwOlJlcG9zaXRvcnkxMjcyMzgzMzU="
open_issues_within = 100
private = false
pushed_within = "year"
stargazers_within = 10
topics = [ ]
updated_within = "year"
watchers_within = 10

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
