code_url = "https://github.com/codeforsanjose/Organizational-Development"
description = "Goals defined by the leadership team that all members are welcome to contribute to."
git_url = "git://github.com/codeforsanjose/Organizational-Development.git"
name = "Organizational-Development"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2016-07-23T21:14:28Z"
default_branch = "master"
description = "Goals defined by the leadership team that all members are welcome to contribute to."
disabled = false
fork = false
forks_within = 0
full_name = "codeforsanjose/Organizational-Development"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 64_036_366
language = { }
license = { }
name = "Organizational-Development"
node_id = "MDEwOlJlcG9zaXRvcnk2NDAzNjM2Ng=="
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
