code_url = "https://github.com/codeforsanjose/Project-Ideas"
description = "Hey have an idea for a Project?  Post it here! See the Waffle version here: "
git_url = "git://github.com/codeforsanjose/Project-Ideas.git"
link_url = "https://waffle.io/codeforsanjose/Project-Ideas"
name = "Project-Ideas"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2015-03-05T20:25:42Z"
default_branch = "master"
description = "Hey have an idea for a Project?  Post it here! See the Waffle version here: "
disabled = false
fork = false
forks_within = 10
full_name = "codeforsanjose/Project-Ideas"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = "https://waffle.io/codeforsanjose/Project-Ideas"
id = 31_734_571
language = { }
license = { }
name = "Project-Ideas"
node_id = "MDEwOlJlcG9zaXRvcnkzMTczNDU3MQ=="
open_issues_within = 100
private = false
pushed_within = "over_a_year"
stargazers_within = 100
topics = [ ]
updated_within = "year"
watchers_within = 100

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
