code_url = "https://github.com/codeforsanjose/python-legistar-scraper"
description = "Scrapes municipal data from Legistar websites"
git_url = "git://github.com/codeforsanjose/python-legistar-scraper.git"
name = "python-legistar-scraper"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2017-10-13T03:01:18Z"
default_branch = "master"
description = "Scrapes municipal data from Legistar websites"
disabled = false
fork = true
forks_within = 0
full_name = "codeforsanjose/python-legistar-scraper"
has_downloads = true
has_issues = false
has_pages = false
has_projects = true
has_wiki = false
homepage = { }
id = 106_771_281
language = "Python"
name = "python-legistar-scraper"
node_id = "MDEwOlJlcG9zaXRvcnkxMDY3NzEyODE="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.license]
  key = "bsd-3-clause"
  name = 'BSD 3-Clause "New" or "Revised" License'
  node_id = "MDc6TGljZW5zZTU="
  spdx_id = "BSD-3-Clause"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
