code_url = "https://github.com/codeforsanjose/scrapers-us-municipal"
description = "Scrapers for US municipal governments."
git_url = "git://github.com/codeforsanjose/scrapers-us-municipal.git"
name = "scrapers-us-municipal"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2017-10-13T03:13:12Z"
default_branch = "master"
description = "Scrapers for US municipal governments."
disabled = false
fork = true
forks_within = 0
full_name = "codeforsanjose/scrapers-us-municipal"
has_downloads = true
has_issues = false
has_pages = false
has_projects = true
has_wiki = false
homepage = ""
id = 106_772_334
language = "Python"
license = { }
name = "scrapers-us-municipal"
node_id = "MDEwOlJlcG9zaXRvcnkxMDY3NzIzMzQ="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
