code_url = "https://github.com/codeforsanjose/sidewalk-widths"
description = "A map of the widths of sidewalks in San Jose, California"
git_url = "git://github.com/codeforsanjose/sidewalk-widths.git"
link_url = "https://www.codeforsanjose.com/sidewalk-widths/"
name = "sidewalk-widths"
organization_name = "Code for San Jose"
topics = [
  "gis",
  "html",
  "mapbox",
  "openstreetmap",
  "postgresql",
  "san-jose",
  "sidewalkwidth"
]

[github]
archived = false
created_at = "2020-05-01T03:52:48Z"
default_branch = "master"
description = "A map of the widths of sidewalks in San Jose, California"
disabled = false
fork = false
forks_within = 0
full_name = "codeforsanjose/sidewalk-widths"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = true
homepage = "https://www.codeforsanjose.com/sidewalk-widths/"
id = 260_374_538
language = "HTML"
name = "sidewalk-widths"
node_id = "MDEwOlJlcG9zaXRvcnkyNjAzNzQ1Mzg="
open_issues_within = 0
private = false
pushed_within = "year"
stargazers_within = 10
topics = [
  "gis",
  "html",
  "mapbox",
  "openstreetmap",
  "postgresql",
  "san-jose",
  "sidewalkwidth"
]
updated_within = "year"
watchers_within = 10

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
