code_url = "https://github.com/codeforsanjose/SJFoodTruckPermits"
git_url = "git://github.com/codeforsanjose/SJFoodTruckPermits.git"
name = "SJFoodTruckPermits"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2016-08-12T03:21:18Z"
default_branch = "master"
description = { }
disabled = false
fork = false
forks_within = 0
full_name = "codeforsanjose/SJFoodTruckPermits"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = true
homepage = { }
id = 65_519_863
language = "CSS"
license = { }
name = "SJFoodTruckPermits"
node_id = "MDEwOlJlcG9zaXRvcnk2NTUxOTg2Mw=="
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
