code_url = "https://github.com/codeforsanjose/sporkability"
description = ":fork_and_knife: :couplekiss:  Best practices for making projects easy to fork"
git_url = "git://github.com/codeforsanjose/sporkability.git"
name = "sporkability"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2015-10-22T04:33:54Z"
default_branch = "master"
description = ":fork_and_knife: :couplekiss:  Best practices for making projects easy to fork"
disabled = false
fork = true
forks_within = 0
full_name = "codeforsanjose/sporkability"
has_downloads = true
has_issues = false
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 44_722_272
language = { }
name = "sporkability"
node_id = "MDEwOlJlcG9zaXRvcnk0NDcyMjI3Mg=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.license]
  key = "unlicense"
  name = "The Unlicense"
  node_id = "MDc6TGljZW5zZTE1"
  spdx_id = "Unlicense"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
