code_url = "https://github.com/codeforsanjose/Terraform"
description = "IaC"
git_url = "git://github.com/codeforsanjose/Terraform.git"
name = "Terraform"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2020-09-05T16:43:27Z"
default_branch = "master"
description = "IaC"
disabled = false
fork = false
forks_within = 0
full_name = "codeforsanjose/Terraform"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 293_115_569
language = { }
name = "Terraform"
node_id = "MDEwOlJlcG9zaXRvcnkyOTMxMTU1Njk="
open_issues_within = 0
private = false
pushed_within = "year"
stargazers_within = 0
topics = [ ]
updated_within = "year"
watchers_within = 0

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
