code_url = "https://github.com/codeforsanjose/theme-public-c4sf"
description = "Public Theme for Brigadehub, made by Code for San Francisco :bridge_at_night:"
git_url = "git://github.com/codeforsanjose/theme-public-c4sf.git"
name = "theme-public-c4sf"
organization_name = "Code for San Jose"
topics = [ "inactive", "website" ]

[github]
archived = false
created_at = "2016-12-06T03:20:47Z"
default_branch = "master"
description = "Public Theme for Brigadehub, made by Code for San Francisco :bridge_at_night:"
disabled = false
fork = true
forks_within = 0
full_name = "codeforsanjose/theme-public-c4sf"
has_downloads = true
has_issues = false
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 75_690_381
language = "JavaScript"
license = { }
name = "theme-public-c4sf"
node_id = "MDEwOlJlcG9zaXRvcnk3NTY5MDM4MQ=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ "inactive", "website" ]
updated_within = "over_a_year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
