code_url = "https://github.com/codeforsanjose/VTA-City_Analysis"
description = "This project is connecting VTA's ridership with local traffic data within VTA's public transportation service"
git_url = "git://github.com/codeforsanjose/VTA-City_Analysis.git"
name = "VTA-City_Analysis"
organization_name = "Code for San Jose"

[github]
archived = false
created_at = "2016-07-15T10:30:26Z"
default_branch = "master"
description = "This project is connecting VTA's ridership with local traffic data within VTA's public transportation service"
disabled = false
fork = false
forks_within = 0
full_name = "codeforsanjose/VTA-City_Analysis"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 63_413_922
language = { }
license = { }
name = "VTA-City_Analysis"
node_id = "MDEwOlJlcG9zaXRvcnk2MzQxMzkyMg=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 6_627_417
  login = "codeforsanjose"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY2Mjc0MTc="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
