code_url = "https://github.com/code4romania/deploy-scripts"
description = "Deployment scripts for Code for Romania projects"
git_url = "git://github.com/code4romania/deploy-scripts.git"
name = "deploy-scripts"
organization_name = "Code for Romania"

[github]
archived = false
created_at = "2020-02-01T08:00:42Z"
default_branch = "master"
description = "Deployment scripts for Code for Romania projects"
disabled = false
fork = false
forks_within = 0
full_name = "code4romania/deploy-scripts"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 237_582_292
language = { }
name = "deploy-scripts"
node_id = "MDEwOlJlcG9zaXRvcnkyMzc1ODIyOTI="
open_issues_within = 0
private = false
pushed_within = "year"
stargazers_within = 0
topics = [ ]
updated_within = "year"
watchers_within = 0

  [github.license]
  key = "mpl-2.0"
  name = "Mozilla Public License 2.0"
  node_id = "MDc6TGljZW5zZTE0"
  spdx_id = "MPL-2.0"

  [github.owner]
  gravatar_id = ""
  id = 18_010_308
  login = "code4romania"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjE4MDEwMzA4"
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
