code_url = "https://github.com/code4romania/rezultate-vot"
description = "Romanian partial election results app. The role of the project is to offer real time aggregated results based on partial information published by BEC (Biroul Electoral Central)"
git_url = "git://github.com/code4romania/rezultate-vot.git"
name = "rezultate-vot"
organization_name = "Code for Romania"

[github]
archived = false
created_at = "2019-05-28T15:01:50Z"
default_branch = "master"
description = "Romanian partial election results app. The role of the project is to offer real time aggregated results based on partial information published by BEC (Biroul Electoral Central)"
disabled = false
fork = false
forks_within = 100
full_name = "code4romania/rezultate-vot"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 189_050_575
language = "C#"
name = "rezultate-vot"
node_id = "MDEwOlJlcG9zaXRvcnkxODkwNTA1NzU="
open_issues_within = 100
private = false
pushed_within = "year"
stargazers_within = 100
topics = [ ]
updated_within = "month"
watchers_within = 100

  [github.license]
  key = "mpl-2.0"
  name = "Mozilla Public License 2.0"
  node_id = "MDc6TGljZW5zZTE0"
  spdx_id = "MPL-2.0"

  [github.owner]
  gravatar_id = ""
  id = 18_010_308
  login = "code4romania"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjE4MDEwMzA4"
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
