code_url = "https://github.com/presidential-innovation-fellows/covid19-travel-advisor"
git_url = "git://github.com/presidential-innovation-fellows/covid19-travel-advisor.git"
name = "covid19-travel-advisor"
organization_name = "Presidential Innovation Fellows"

[github]
archived = false
created_at = "2020-07-29T18:08:25Z"
default_branch = "master"
description = { }
disabled = false
fork = false
forks_within = 0
full_name = "presidential-innovation-fellows/covid19-travel-advisor"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 283_569_471
language = "CSS"
name = "covid19-travel-advisor"
node_id = "MDEwOlJlcG9zaXRvcnkyODM1Njk0NzE="
open_issues_within = 0
private = false
pushed_within = "year"
stargazers_within = 0
topics = [ ]
updated_within = "year"
watchers_within = 0

  [github.license]
  key = "cc0-1.0"
  name = "Creative Commons Zero v1.0 Universal"
  node_id = "MDc6TGljZW5zZTY="
  spdx_id = "CC0-1.0"

  [github.owner]
  gravatar_id = ""
  id = 2_146_920
  login = "presidential-innovation-fellows"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjIxNDY5MjA="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
