code_url = "https://github.com/CodeForAsheville/brigade"
description = "Brigade Platform"
git_url = "git://github.com/CodeForAsheville/brigade.git"
link_url = "brigade.codeforamerica.org"
name = "brigade"
organization_name = "Code for Asheville"

[github]
archived = false
created_at = "2013-03-22T15:10:43Z"
default_branch = "master"
description = "Brigade Platform"
disabled = false
fork = true
forks_within = 0
full_name = "CodeForAsheville/brigade"
has_downloads = true
has_issues = false
has_pages = false
has_projects = true
has_wiki = true
homepage = "brigade.codeforamerica.org"
id = 8_954_500
language = "Ruby"
name = "brigade"
node_id = "MDEwOlJlcG9zaXRvcnk4OTU0NTAw"
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.license]
  key = "bsd-3-clause"
  name = 'BSD 3-Clause "New" or "Revised" License'
  node_id = "MDc6TGljZW5zZTU="
  spdx_id = "BSD-3-Clause"

  [github.owner]
  gravatar_id = ""
  id = 3_941_752
  login = "CodeForAsheville"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjM5NDE3NTI="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
