code_url = "https://github.com/CodeForAsheville/cfa-projects-page"
description = "A page listing the projects that Code for Asheville is working on."
git_url = "git://github.com/CodeForAsheville/cfa-projects-page.git"
name = "cfa-projects-page"
organization_name = "Code for Asheville"

[github]
archived = false
created_at = "2016-12-18T18:06:15Z"
default_branch = "master"
description = "A page listing the projects that Code for Asheville is working on."
disabled = false
fork = false
forks_within = 0
full_name = "CodeForAsheville/cfa-projects-page"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 76_798_466
language = "JavaScript"
name = "cfa-projects-page"
node_id = "MDEwOlJlcG9zaXRvcnk3Njc5ODQ2Ng=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.license]
  key = "gpl-3.0"
  name = "GNU General Public License v3.0"
  node_id = "MDc6TGljZW5zZTk="
  spdx_id = "GPL-3.0"

  [github.owner]
  gravatar_id = ""
  id = 3_941_752
  login = "CodeForAsheville"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjM5NDE3NTI="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
