code_url = "https://github.com/CodeForAsheville/HackForFoodData"
description = "data to support hack for food"
git_url = "git://github.com/CodeForAsheville/HackForFoodData.git"
name = "HackForFoodData"
organization_name = "Code for Asheville"

[github]
archived = false
created_at = "2013-04-09T14:07:33Z"
default_branch = "master"
description = "data to support hack for food"
disabled = false
fork = false
forks_within = 10
full_name = "CodeForAsheville/HackForFoodData"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 9_322_644
language = "JavaScript"
license = { }
name = "HackForFoodData"
node_id = "MDEwOlJlcG9zaXRvcnk5MzIyNjQ0"
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 3_941_752
  login = "CodeForAsheville"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjM5NDE3NTI="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
