code_url = "https://github.com/CodeForAsheville/muni"
description = "Next Muni API Client."
git_url = "git://github.com/CodeForAsheville/muni.git"
link_url = "http://jeffremer.com/muni"
name = "muni"
organization_name = "Code for Asheville"

[github]
archived = false
created_at = "2014-05-08T21:18:08Z"
default_branch = "master"
description = "Next Muni API Client."
disabled = false
fork = true
forks_within = 0
full_name = "CodeForAsheville/muni"
has_downloads = true
has_issues = false
has_pages = false
has_projects = true
has_wiki = true
homepage = "http://jeffremer.com/muni"
id = 19_589_243
language = "Ruby"
name = "muni"
node_id = "MDEwOlJlcG9zaXRvcnkxOTU4OTI0Mw=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 3_941_752
  login = "CodeForAsheville"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjM5NDE3NTI="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
