code_url = "https://github.com/CodeForAsheville/open-data-etl-utility-kit"
description = "Use Pentaho's open source data integration tool (Kettle) to create Extract-Transform-Load (ETL) processes to update a Socrata open data portal. Documentation is available at http://open-data-etl-utility-kit.readthedocs.org/en/latest/"
git_url = "git://github.com/CodeForAsheville/open-data-etl-utility-kit.git"
name = "open-data-etl-utility-kit"
organization_name = "Code for Asheville"

[github]
archived = false
created_at = "2014-09-25T17:17:15Z"
default_branch = "master"
description = "Use Pentaho's open source data integration tool (Kettle) to create Extract-Transform-Load (ETL) processes to update a Socrata open data portal. Documentation is available at http://open-data-etl-utility-kit.readthedocs.org/en/latest/"
disabled = false
fork = true
forks_within = 0
full_name = "CodeForAsheville/open-data-etl-utility-kit"
has_downloads = true
has_issues = false
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 24_467_730
language = { }
name = "open-data-etl-utility-kit"
node_id = "MDEwOlJlcG9zaXRvcnkyNDQ2NzczMA=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.license]
  key = "other"
  name = "Other"
  node_id = "MDc6TGljZW5zZTA="
  spdx_id = "NOASSERTION"

  [github.owner]
  gravatar_id = ""
  id = 3_941_752
  login = "CodeForAsheville"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjM5NDE3NTI="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
