code_url = "https://github.com/CodeForAsheville/voting-meteor"
git_url = "git://github.com/CodeForAsheville/voting-meteor.git"
name = "voting-meteor"
organization_name = "Code for Asheville"

[github]
archived = false
created_at = "2015-01-17T16:56:48Z"
default_branch = "master"
description = { }
disabled = false
fork = false
forks_within = 10
full_name = "CodeForAsheville/voting-meteor"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 29_398_026
language = "JavaScript"
license = { }
name = "voting-meteor"
node_id = "MDEwOlJlcG9zaXRvcnkyOTM5ODAyNg=="
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 3_941_752
  login = "CodeForAsheville"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjM5NDE3NTI="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
