code_url = "https://github.com/CodeForAsheville/wordpress"
git_url = "git://github.com/CodeForAsheville/wordpress.git"
name = "wordpress"
organization_name = "Code for Asheville"

[github]
archived = false
created_at = "2014-04-22T23:15:06Z"
default_branch = "production"
description = { }
disabled = false
fork = false
forks_within = 0
full_name = "CodeForAsheville/wordpress"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 19_049_789
language = "PHP"
name = "wordpress"
node_id = "MDEwOlJlcG9zaXRvcnkxOTA0OTc4OQ=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.license]
  key = "other"
  name = "Other"
  node_id = "MDc6TGljZW5zZTA="
  spdx_id = "NOASSERTION"

  [github.owner]
  gravatar_id = ""
  id = 3_941_752
  login = "CodeForAsheville"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjM5NDE3NTI="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
