code_url = "https://github.com/mysociety/caps"
git_url = "git://github.com/mysociety/caps.git"
name = "caps"
organization_name = "mySociety"

[github]
archived = false
created_at = "2020-08-21T20:17:51Z"
default_branch = "master"
description = { }
disabled = false
fork = false
forks_within = 0
full_name = "mysociety/caps"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = true
homepage = { }
id = 289_357_345
language = "Python"
license = { }
name = "caps"
node_id = "MDEwOlJlcG9zaXRvcnkyODkzNTczNDU="
open_issues_within = 10
private = false
pushed_within = "week"
stargazers_within = 0
topics = [ ]
updated_within = "month"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 141_338
  login = "mysociety"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjE0MTMzOA=="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
