code_url = "https://github.com/codeforct/clean-slate-ct"
description = "This project is cloned from https://www.codeforbtv.org/projects/expunge-vt and is made available for the purpose of exploring the viability of a similar tool that can be used to facilitate the process of applying for a criminal record pardon in Connecticut."
git_url = "git://github.com/codeforct/clean-slate-ct.git"
name = "clean-slate-ct"
organization_name = "Code for Connecticut"

[github]
archived = false
created_at = "2020-01-22T01:15:49Z"
default_branch = "master"
description = "This project is cloned from https://www.codeforbtv.org/projects/expunge-vt and is made available for the purpose of exploring the viability of a similar tool that can be used to facilitate the process of applying for a criminal record pardon in Connecticut."
disabled = false
fork = false
forks_within = 0
full_name = "codeforct/clean-slate-ct"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 235_474_250
language = "HTML"
name = "clean-slate-ct"
node_id = "MDEwOlJlcG9zaXRvcnkyMzU0NzQyNTA="
open_issues_within = 0
private = false
pushed_within = "year"
stargazers_within = 0
topics = [ ]
updated_within = "year"
watchers_within = 0

  [github.license]
  key = "apache-2.0"
  name = "Apache License 2.0"
  node_id = "MDc6TGljZW5zZTI="
  spdx_id = "Apache-2.0"

  [github.owner]
  gravatar_id = ""
  id = 50_676_221
  login = "codeforct"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjUwNjc2MjIx"
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
