code_url = "https://github.com/codeforct/codeofconduct"
description = "Code for America's Code of Conduct"
git_url = "git://github.com/codeforct/codeofconduct.git"
name = "codeofconduct"
organization_name = "Code for Connecticut"

[github]
archived = false
created_at = "2019-07-23T15:16:21Z"
default_branch = "master"
description = "Code for America's Code of Conduct"
disabled = false
fork = true
forks_within = 0
full_name = "codeforct/codeofconduct"
has_downloads = true
has_issues = false
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 198_455_995
language = { }
license = { }
name = "codeofconduct"
node_id = "MDEwOlJlcG9zaXRvcnkxOTg0NTU5OTU="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 50_676_221
  login = "codeforct"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjUwNjc2MjIx"
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
