code_url = "https://github.com/codeforct/KnowYourRights"
description = "Know Your Rights website for justice-impacted citizens of Connecticut"
git_url = "git://github.com/codeforct/KnowYourRights.git"
name = "KnowYourRights"
organization_name = "Code for Connecticut"

[github]
archived = false
created_at = "2019-09-21T19:07:53Z"
default_branch = "master"
description = "Know Your Rights website for justice-impacted citizens of Connecticut"
disabled = false
fork = false
forks_within = 0
full_name = "codeforct/KnowYourRights"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = true
homepage = { }
id = 210_039_806
language = "CSS"
name = "KnowYourRights"
node_id = "MDEwOlJlcG9zaXRvcnkyMTAwMzk4MDY="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.license]
  key = "apache-2.0"
  name = "Apache License 2.0"
  node_id = "MDc6TGljZW5zZTI="
  spdx_id = "Apache-2.0"

  [github.owner]
  gravatar_id = ""
  id = 50_676_221
  login = "codeforct"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjUwNjc2MjIx"
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
