description = "A site that helps people access information about and apply for affordable housing in one platform."
link_url = "http://housing.smcgov.org/san-mateo-county-affordable-rental-housing-list"
name = "Affordable Housing Bay Area"
organization_name = "OpenSMC"
