code_url = "https://github.com/codeformuenster/clustersetup"
git_url = "git://github.com/codeformuenster/clustersetup.git"
name = "clustersetup"
organization_name = "OK Lab Münster"

[github]
archived = false
created_at = "2020-10-15T21:09:09Z"
default_branch = "main"
description = { }
disabled = false
fork = false
forks_within = 0
full_name = "codeformuenster/clustersetup"
has_downloads = true
has_issues = true
has_pages = false
has_projects = false
has_wiki = false
homepage = { }
id = 304_448_636
language = { }
name = "clustersetup"
node_id = "MDEwOlJlcG9zaXRvcnkzMDQ0NDg2MzY="
open_issues_within = 0
private = false
pushed_within = "week"
stargazers_within = 0
topics = [ ]
updated_within = "week"
watchers_within = 0

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_464_842
  login = "codeformuenster"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY0NjQ4NDI="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
