code_url = "https://github.com/codeformuenster/muenster-runnermap"
description = "Eine visuelle Darstellung der populärsten Jogging-Routen in Münster."
git_url = "git://github.com/codeformuenster/muenster-runnermap.git"
link_url = "http://codeformuenster.github.io/muenster-runnermap/"
name = "muenster-runnermap"
organization_name = "OK Lab Münster"

[github]
archived = false
created_at = "2014-02-22T10:21:07Z"
default_branch = "master"
description = "Eine visuelle Darstellung der populärsten Jogging-Routen in Münster."
disabled = false
fork = false
forks_within = 10
full_name = "codeformuenster/muenster-runnermap"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = true
homepage = "http://codeformuenster.github.io/muenster-runnermap/"
id = 17_082_621
language = "Objective-C"
license = { }
name = "muenster-runnermap"
node_id = "MDEwOlJlcG9zaXRvcnkxNzA4MjYyMQ=="
open_issues_within = 10
private = false
pushed_within = "year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 6_464_842
  login = "codeformuenster"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY0NjQ4NDI="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
