code_url = "https://github.com/codeformuenster/wahlkarte"
description = "Grafische Darstellung der Ergebnisse der Kommunalwahl Münster 2014."
git_url = "git://github.com/codeformuenster/wahlkarte.git"
link_url = "http://codeformuenster.org/wahlkarte/"
name = "wahlkarte"
organization_name = "OK Lab Münster"

[github]
archived = false
created_at = "2014-05-14T20:29:02Z"
default_branch = "gh-pages"
description = "Grafische Darstellung der Ergebnisse der Kommunalwahl Münster 2014."
disabled = false
fork = false
forks_within = 10
full_name = "codeformuenster/wahlkarte"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = true
homepage = "http://codeformuenster.org/wahlkarte/"
id = 19_795_084
language = "CSS"
license = { }
name = "wahlkarte"
node_id = "MDEwOlJlcG9zaXRvcnkxOTc5NTA4NA=="
open_issues_within = 100
private = false
pushed_within = "year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 6_464_842
  login = "codeformuenster"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY0NjQ4NDI="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
