code_url = "https://github.com/CodeandoMexico/hackathon-book"
description = "Hackathon: the missing guide"
git_url = "git://github.com/CodeandoMexico/hackathon-book.git"
name = "hackathon-book"
organization_name = "Codeando México"

[github]
archived = false
created_at = "2014-10-14T01:53:08Z"
default_branch = "master"
description = "Hackathon: the missing guide"
disabled = false
fork = false
forks_within = 0
full_name = "CodeandoMexico/hackathon-book"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 25_185_871
language = { }
license = { }
name = "hackathon-book"
node_id = "MDEwOlJlcG9zaXRvcnkyNTE4NTg3MQ=="
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 2_940_113
  login = "CodeandoMexico"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjI5NDAxMTM="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
