code_url = "https://github.com/codefordayton/diyfacemask"
git_url = "git://github.com/codefordayton/diyfacemask.git"
name = "diyfacemask"
organization_name = "Code for Dayton"

[github]
archived = false
created_at = "2020-03-21T20:08:39Z"
default_branch = "master"
description = { }
disabled = false
fork = false
forks_within = 0
full_name = "codefordayton/diyfacemask"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 249_052_268
language = "HTML"
name = "diyfacemask"
node_id = "MDEwOlJlcG9zaXRvcnkyNDkwNTIyNjg="
open_issues_within = 10
private = false
pushed_within = "year"
stargazers_within = 0
topics = [ ]
updated_within = "year"
watchers_within = 0

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_026_408
  login = "codefordayton"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjYwMjY0MDg="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
