code_url = "https://github.com/codeforrva/flushot-map"
git_url = "git://github.com/codeforrva/flushot-map.git"
name = "flushot-map"
organization_name = "Code for RVA"

[github]
archived = false
created_at = "2014-11-27T04:11:48Z"
default_branch = "master"
description = { }
disabled = false
fork = false
forks_within = 0
full_name = "codeforrva/flushot-map"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 27_208_515
language = "CSS"
name = "flushot-map"
node_id = "MDEwOlJlcG9zaXRvcnkyNzIwODUxNQ=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.license]
  key = "apache-2.0"
  name = "Apache License 2.0"
  node_id = "MDc6TGljZW5zZTI="
  spdx_id = "Apache-2.0"

  [github.owner]
  gravatar_id = ""
  id = 6_845_795
  login = "codeforrva"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjY4NDU3OTU="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
