code_url = "https://github.com/OpenUpSA/pocketreporter"
description = "A tool for helping young reporters write better stories."
git_url = "git://github.com/OpenUpSA/pocketreporter.git"
link_url = "http://pocketreporter.co.za"
name = "pocketreporter"
organization_name = "OpenUp"
topics = [ "backbonejs", "journalism", "phonegap" ]

[github]
archived = false
created_at = "2016-06-21T18:34:46Z"
default_branch = "app"
description = "A tool for helping young reporters write better stories."
disabled = false
fork = false
forks_within = 10
full_name = "OpenUpSA/pocketreporter"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = true
homepage = "http://pocketreporter.co.za"
id = 61_657_596
language = "JavaScript"
name = "pocketreporter"
node_id = "MDEwOlJlcG9zaXRvcnk2MTY1NzU5Ng=="
open_issues_within = 10
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ "backbonejs", "journalism", "phonegap" ]
updated_within = "over_a_year"
watchers_within = 10

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 26_482_663
  login = "OpenUpSA"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjI2NDgyNjYz"
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
