code_url = "https://github.com/OpenUpSA/wazimap-ng"
git_url = "git://github.com/OpenUpSA/wazimap-ng.git"
name = "wazimap-ng"
organization_name = "OpenUp"

[github]
archived = false
created_at = "2019-12-21T13:58:37Z"
default_branch = "staging"
description = { }
disabled = false
fork = false
forks_within = 10
full_name = "OpenUpSA/wazimap-ng"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 229_435_119
language = "Python"
name = "wazimap-ng"
node_id = "MDEwOlJlcG9zaXRvcnkyMjk0MzUxMTk="
open_issues_within = 100
private = false
pushed_within = "week"
stargazers_within = 10
topics = [ ]
updated_within = "week"
watchers_within = 10

  [github.license]
  key = "apache-2.0"
  name = "Apache License 2.0"
  node_id = "MDc6TGljZW5zZTI="
  spdx_id = "Apache-2.0"

  [github.owner]
  gravatar_id = ""
  id = 26_482_663
  login = "OpenUpSA"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjI2NDgyNjYz"
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
