code_url = "https://github.com/OpenUpSA/webflow-import"
description = "A simple tool to import a Webflow site export to another project"
git_url = "git://github.com/OpenUpSA/webflow-import.git"
name = "webflow-import"
organization_name = "OpenUp"

[github]
archived = false
created_at = "2020-05-16T13:13:39Z"
default_branch = "master"
description = "A simple tool to import a Webflow site export to another project"
disabled = false
fork = false
forks_within = 0
full_name = "OpenUpSA/webflow-import"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 264_440_533
language = "Python"
name = "webflow-import"
node_id = "MDEwOlJlcG9zaXRvcnkyNjQ0NDA1MzM="
open_issues_within = 0
private = false
pushed_within = "year"
stargazers_within = 0
topics = [ ]
updated_within = "year"
watchers_within = 0

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 26_482_663
  login = "OpenUpSA"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjI2NDgyNjYz"
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
