code_url = "https://github.com/codeforboston/jobhopper"
git_url = "git://github.com/codeforboston/jobhopper.git"
name = "jobhopper"
organization_name = "Code for Boston"

[github]
archived = false
created_at = "2020-03-16T21:46:59Z"
default_branch = "master"
description = { }
disabled = false
fork = false
forks_within = 100
full_name = "codeforboston/jobhopper"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 247_822_717
language = "Python"
name = "jobhopper"
node_id = "MDEwOlJlcG9zaXRvcnkyNDc4MjI3MTc="
open_issues_within = 100
private = false
pushed_within = "week"
stargazers_within = 10
topics = [ ]
updated_within = "week"
watchers_within = 10

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 2_533_182
  login = "codeforboston"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjI1MzMxODI="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
