code_url = "https://github.com/18F/10x-workshare"
description = "10x Phase 2 Investigation: Workshare Unemployment Program"
git_url = "git://github.com/18F/10x-workshare.git"
name = "10x-workshare"
organization_name = "18F"
topics = [
  "10x",
  "18f",
  "data",
  "jobs",
  "labor",
  "technology",
  "unemployment",
  "workshare"
]

[github]
archived = false
created_at = "2020-07-24T16:25:17Z"
default_branch = "master"
description = "10x Phase 2 Investigation: Workshare Unemployment Program"
disabled = false
fork = false
forks_within = 0
full_name = "18F/10x-workshare"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 282_267_239
language = { }
license = { }
name = "10x-workshare"
node_id = "MDEwOlJlcG9zaXRvcnkyODIyNjcyMzk="
open_issues_within = 0
private = false
pushed_within = "year"
stargazers_within = 0
topics = [
  "10x",
  "18f",
  "data",
  "jobs",
  "labor",
  "technology",
  "unemployment",
  "workshare"
]
updated_within = "year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 6_233_994
  login = "18F"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjYyMzM5OTQ="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
