code_url = "https://github.com/18F/10x-dux-app"
description = "The 10x Dependency Upgrades eXample App. More background in the main repository. See link below."
git_url = "git://github.com/18F/10x-dux-app.git"
link_url = "https://github.com/18F/10x-dux-vuls-eval"
name = "10x-dux-app"
organization_name = "18F"

[github]
archived = false
created_at = "2020-04-20T20:43:30Z"
default_branch = "develop"
description = "The 10x Dependency Upgrades eXample App. More background in the main repository. See link below."
disabled = false
fork = false
forks_within = 10
full_name = "18F/10x-dux-app"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = "https://github.com/18F/10x-dux-vuls-eval"
id = 257_399_206
language = "Python"
name = "10x-dux-app"
node_id = "MDEwOlJlcG9zaXRvcnkyNTczOTkyMDY="
open_issues_within = 10
private = false
pushed_within = "week"
stargazers_within = 10
topics = [ ]
updated_within = "month"
watchers_within = 10

  [github.license]
  key = "other"
  name = "Other"
  node_id = "MDc6TGljZW5zZTA="
  spdx_id = "NOASSERTION"

  [github.owner]
  gravatar_id = ""
  id = 6_233_994
  login = "18F"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjYyMzM5OTQ="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
