code_url = "https://github.com/18F/10x-dux-vuls-eval"
description = "Infrastructure for 10x-dux-app analysis with the vuls.io toolset."
git_url = "git://github.com/18F/10x-dux-vuls-eval.git"
name = "10x-dux-vuls-eval"
organization_name = "18F"

[github]
archived = false
created_at = "2020-05-01T03:29:12Z"
default_branch = "master"
description = "Infrastructure for 10x-dux-app analysis with the vuls.io toolset."
disabled = false
fork = false
forks_within = 0
full_name = "18F/10x-dux-vuls-eval"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 260_371_480
language = "HCL"
name = "10x-dux-vuls-eval"
node_id = "MDEwOlJlcG9zaXRvcnkyNjAzNzE0ODA="
open_issues_within = 10
private = false
pushed_within = "month"
stargazers_within = 10
topics = [ ]
updated_within = "week"
watchers_within = 10

  [github.license]
  key = "other"
  name = "Other"
  node_id = "MDc6TGljZW5zZTA="
  spdx_id = "NOASSERTION"

  [github.owner]
  gravatar_id = ""
  id = 6_233_994
  login = "18F"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjYyMzM5OTQ="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
