code_url = "https://github.com/18F/18f-eslint"
description = "18F eslint configuration"
git_url = "git://github.com/18F/18f-eslint.git"
link_url = "https://engineering.18f.gov/javascript/style/"
name = "18f-eslint"
organization_name = "18F"

[github]
archived = false
created_at = "2020-10-13T00:07:37Z"
default_branch = "main"
description = "18F eslint configuration"
disabled = false
fork = false
forks_within = 0
full_name = "18F/18f-eslint"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = "https://engineering.18f.gov/javascript/style/"
id = 303_542_392
language = "JavaScript"
name = "18f-eslint"
node_id = "MDEwOlJlcG9zaXRvcnkzMDM1NDIzOTI="
open_issues_within = 0
private = false
pushed_within = "month"
stargazers_within = 0
topics = [ ]
updated_within = "month"
watchers_within = 0

  [github.license]
  key = "other"
  name = "Other"
  node_id = "MDc6TGljZW5zZTA="
  spdx_id = "NOASSERTION"

  [github.owner]
  gravatar_id = ""
  id = 6_233_994
  login = "18F"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjYyMzM5OTQ="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
