code_url = "https://github.com/18F/all_sorns"
description = "Prototyping for 10x - Privacy Dashboard team"
git_url = "git://github.com/18F/all_sorns.git"
name = "all_sorns"
organization_name = "18F"

[github]
archived = false
created_at = "2020-09-17T18:01:03Z"
default_branch = "main"
description = "Prototyping for 10x - Privacy Dashboard team"
disabled = false
fork = false
forks_within = 0
full_name = "18F/all_sorns"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 296_403_774
language = "Ruby"
license = { }
name = "all_sorns"
node_id = "MDEwOlJlcG9zaXRvcnkyOTY0MDM3NzQ="
open_issues_within = 10
private = false
pushed_within = "week"
stargazers_within = 10
topics = [ ]
updated_within = "week"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 6_233_994
  login = "18F"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjYyMzM5OTQ="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
