code_url = "https://github.com/18F/alpine-fips"
description = "Alpine Linux with FIPS 140-2 OpenSSL"
git_url = "git://github.com/18F/alpine-fips.git"
name = "alpine-fips"
organization_name = "18F"

[github]
archived = false
created_at = "2020-10-07T21:15:22Z"
default_branch = "master"
description = "Alpine Linux with FIPS 140-2 OpenSSL"
disabled = false
fork = true
forks_within = 0
full_name = "18F/alpine-fips"
has_downloads = true
has_issues = false
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 302_162_032
language = "Dockerfile"
license = { }
name = "alpine-fips"
node_id = "MDEwOlJlcG9zaXRvcnkzMDIxNjIwMzI="
open_issues_within = 0
private = false
pushed_within = "month"
stargazers_within = 0
topics = [ ]
updated_within = "month"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 6_233_994
  login = "18F"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjYyMzM5OTQ="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
