code_url = "https://github.com/18F/civil-rights-complaints"
description = "A working space for 18F's engagement with the DOJ CRT to develop a civil rights complaint portal"
git_url = "git://github.com/18F/civil-rights-complaints.git"
name = "civil-rights-complaints"
organization_name = "18F"

[github]
archived = false
created_at = "2018-11-21T23:01:38Z"
default_branch = "master"
description = "A working space for 18F's engagement with the DOJ CRT to develop a civil rights complaint portal"
disabled = false
fork = false
forks_within = 0
full_name = "18F/civil-rights-complaints"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 158_615_967
language = { }
name = "civil-rights-complaints"
node_id = "MDEwOlJlcG9zaXRvcnkxNTg2MTU5Njc="
open_issues_within = 100
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "year"
watchers_within = 10

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_233_994
  login = "18F"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjYyMzM5OTQ="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
