code_url = "https://github.com/18F/cms-carts-seds"
description = "18F/CMS CARTS & SEDS redevelopment"
git_url = "git://github.com/18F/cms-carts-seds.git"
name = "cms-carts-seds"
organization_name = "18F"

[github]
archived = false
created_at = "2019-12-06T19:56:57Z"
default_branch = "master"
description = "18F/CMS CARTS & SEDS redevelopment"
disabled = false
fork = false
forks_within = 10
full_name = "18F/cms-carts-seds"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 226_399_669
language = "JavaScript"
license = { }
name = "cms-carts-seds"
node_id = "MDEwOlJlcG9zaXRvcnkyMjYzOTk2Njk="
open_issues_within = 1_000
private = false
pushed_within = "week"
stargazers_within = 10
topics = [ ]
updated_within = "week"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 6_233_994
  login = "18F"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjYyMzM5OTQ="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
