code_url = "https://github.com/18F/Dot-Net-Encasement"
description = ":shell: Encasing legacy systems using VS Code, C#, .NET Core, and Web API "
git_url = "git://github.com/18F/Dot-Net-Encasement.git"
name = "Dot-Net-Encasement"
organization_name = "18F"
topics = [ "csharp", "dotnet", "legacy", "sql-server", "vscode" ]

[github]
archived = false
created_at = "2020-02-18T23:46:56Z"
default_branch = "master"
description = ":shell: Encasing legacy systems using VS Code, C#, .NET Core, and Web API "
disabled = false
fork = false
forks_within = 0
full_name = "18F/Dot-Net-Encasement"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 241_492_228
language = { }
name = "Dot-Net-Encasement"
node_id = "MDEwOlJlcG9zaXRvcnkyNDE0OTIyMjg="
open_issues_within = 10
private = false
pushed_within = "year"
stargazers_within = 10
topics = [ "csharp", "dotnet", "legacy", "sql-server", "vscode" ]
updated_within = "year"
watchers_within = 10

  [github.license]
  key = "other"
  name = "Other"
  node_id = "MDc6TGljZW5zZTA="
  spdx_id = "NOASSERTION"

  [github.owner]
  gravatar_id = ""
  id = 6_233_994
  login = "18F"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjYyMzM5OTQ="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
