code_url = "https://github.com/18F/formservice.gsa.gov"
git_url = "git://github.com/18F/formservice.gsa.gov.git"
name = "formservice.gsa.gov"
organization_name = "18F"

[github]
archived = false
created_at = "2020-09-10T15:56:18Z"
default_branch = "master"
description = { }
disabled = false
fork = false
forks_within = 10
full_name = "18F/formservice.gsa.gov"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 294_455_874
language = { }
name = "formservice.gsa.gov"
node_id = "MDEwOlJlcG9zaXRvcnkyOTQ0NTU4NzQ="
open_issues_within = 0
private = false
pushed_within = "year"
stargazers_within = 10
topics = [ ]
updated_within = "month"
watchers_within = 10

  [github.license]
  key = "other"
  name = "Other"
  node_id = "MDc6TGljZW5zZTA="
  spdx_id = "NOASSERTION"

  [github.owner]
  gravatar_id = ""
  id = 6_233_994
  login = "18F"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjYyMzM5OTQ="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
