code_url = "https://github.com/18F/g-analytics"
description = "Projects of the 18F Analytics Guild. For the 18F analytics standards, visit"
git_url = "git://github.com/18F/g-analytics.git"
link_url = "https://github.com/18F/analytics-standards"
name = "g-analytics"
organization_name = "18F"

[github]
archived = false
created_at = "2014-06-20T20:23:50Z"
default_branch = "18f-pages"
description = "Projects of the 18F Analytics Guild. For the 18F analytics standards, visit"
disabled = false
fork = false
forks_within = 10
full_name = "18F/g-analytics"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = false
homepage = "https://github.com/18F/analytics-standards"
id = 21_051_286
language = "Python"
name = "g-analytics"
node_id = "MDEwOlJlcG9zaXRvcnkyMTA1MTI4Ng=="
open_issues_within = 100
private = false
pushed_within = "year"
stargazers_within = 100
topics = [ ]
updated_within = "year"
watchers_within = 100

  [github.license]
  key = "other"
  name = "Other"
  node_id = "MDc6TGljZW5zZTA="
  spdx_id = "NOASSERTION"

  [github.owner]
  gravatar_id = ""
  id = 6_233_994
  login = "18F"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjYyMzM5OTQ="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
