code_url = "https://github.com/18F/hud-erm-ide"
git_url = "git://github.com/18F/hud-erm-ide.git"
name = "hud-erm-ide"
organization_name = "18F"

[github]
archived = false
created_at = "2020-07-30T15:08:44Z"
default_branch = "master"
description = { }
disabled = false
fork = false
forks_within = 0
full_name = "18F/hud-erm-ide"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 283_806_856
language = { }
license = { }
name = "hud-erm-ide"
node_id = "MDEwOlJlcG9zaXRvcnkyODM4MDY4NTY="
open_issues_within = 0
private = false
pushed_within = "year"
stargazers_within = 10
topics = [ ]
updated_within = "year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 6_233_994
  login = "18F"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjYyMzM5OTQ="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
