code_url = "https://github.com/18F/identity-monitor"
description = "smoke test login.gov"
git_url = "git://github.com/18F/identity-monitor.git"
name = "identity-monitor"
organization_name = "18F"
topics = [ "login-gov" ]

[github]
archived = false
created_at = "2016-11-08T20:54:54Z"
default_branch = "master"
description = "smoke test login.gov"
disabled = false
fork = false
forks_within = 10
full_name = "18F/identity-monitor"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 73_226_198
language = "Ruby"
license = { }
name = "identity-monitor"
node_id = "MDEwOlJlcG9zaXRvcnk3MzIyNjE5OA=="
open_issues_within = 0
private = false
pushed_within = "year"
stargazers_within = 10
topics = [ "login-gov" ]
updated_within = "year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 6_233_994
  login = "18F"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjYyMzM5OTQ="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
