code_url = "https://github.com/18F/national-security-portfolio"
description = "An index of 18F and TTS work in the national security & intelligence space"
git_url = "git://github.com/18F/national-security-portfolio.git"
name = "national-security-portfolio"
organization_name = "18F"

[github]
archived = false
created_at = "2019-10-22T19:20:16Z"
default_branch = "master"
description = "An index of 18F and TTS work in the national security & intelligence space"
disabled = false
fork = false
forks_within = 0
full_name = "18F/national-security-portfolio"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 216_892_201
language = { }
license = { }
name = "national-security-portfolio"
node_id = "MDEwOlJlcG9zaXRvcnkyMTY4OTIyMDE="
open_issues_within = 100
private = false
pushed_within = "year"
stargazers_within = 0
topics = [ ]
updated_within = "year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 6_233_994
  login = "18F"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjYyMzM5OTQ="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
