code_url = "https://github.com/18F/paas-codimd"
description = "CodiMD - Realtime collaborative markdown notes on all platforms. Deployable for free testing on https://cloud.gov sandbox"
git_url = "git://github.com/18F/paas-codimd.git"
link_url = "https://github.com/18f/paas-codimd#deploy-to-cloudgov"
name = "paas-codimd"
organization_name = "18F"

[github]
archived = false
created_at = "2020-01-22T22:19:30Z"
default_branch = "master"
description = "CodiMD - Realtime collaborative markdown notes on all platforms. Deployable for free testing on https://cloud.gov sandbox"
disabled = false
fork = true
forks_within = 0
full_name = "18F/paas-codimd"
has_downloads = true
has_issues = false
has_pages = false
has_projects = true
has_wiki = true
homepage = "https://github.com/18f/paas-codimd#deploy-to-cloudgov"
id = 235_678_940
language = "JavaScript"
name = "paas-codimd"
node_id = "MDEwOlJlcG9zaXRvcnkyMzU2Nzg5NDA="
open_issues_within = 10
private = false
pushed_within = "year"
stargazers_within = 10
topics = [ ]
updated_within = "month"
watchers_within = 10

  [github.license]
  key = "agpl-3.0"
  name = "GNU Affero General Public License v3.0"
  node_id = "MDc6TGljZW5zZTE="
  spdx_id = "AGPL-3.0"

  [github.owner]
  gravatar_id = ""
  id = 6_233_994
  login = "18F"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjYyMzM5OTQ="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
