code_url = "https://github.com/18F/piipan"
git_url = "git://github.com/18F/piipan.git"
name = "piipan"
organization_name = "18F"

[github]
archived = false
created_at = "2020-10-19T15:58:25Z"
default_branch = "main"
description = { }
disabled = false
fork = false
forks_within = 0
full_name = "18F/piipan"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 305_438_071
language = { }
license = { }
name = "piipan"
node_id = "MDEwOlJlcG9zaXRvcnkzMDU0MzgwNzE="
open_issues_within = 0
private = false
pushed_within = "week"
stargazers_within = 0
topics = [ ]
updated_within = "week"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 6_233_994
  login = "18F"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjYyMzM5OTQ="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
