code_url = "https://github.com/18F/privacy-tools"
description = "GSA PII Dashboard"
git_url = "git://github.com/18F/privacy-tools.git"
link_url = "https://cg-9341b8ea-025c-4fe2-aa6c-850edbebc499.app.cloud.gov/site/18f/privacy-dashboard/"
name = "privacy-tools"
organization_name = "18F"

[github]
archived = false
created_at = "2020-01-21T17:52:13Z"
default_branch = "master"
description = "GSA PII Dashboard"
disabled = false
fork = false
forks_within = 10
full_name = "18F/privacy-tools"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = "https://cg-9341b8ea-025c-4fe2-aa6c-850edbebc499.app.cloud.gov/site/18f/privacy-dashboard/"
id = 235_405_687
language = "Python"
name = "privacy-tools"
node_id = "MDEwOlJlcG9zaXRvcnkyMzU0MDU2ODc="
open_issues_within = 100
private = false
pushed_within = "year"
stargazers_within = 10
topics = [ ]
updated_within = "month"
watchers_within = 10

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_233_994
  login = "18F"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjYyMzM5OTQ="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
