code_url = "https://github.com/18F/Spotlight-ui"
description = "React/Gatsby frontend to `18F/spotlight/`"
git_url = "git://github.com/18F/Spotlight-ui.git"
name = "Spotlight-ui"
organization_name = "18F"

[github]
archived = false
created_at = "2020-01-17T17:38:50Z"
default_branch = "main"
description = "React/Gatsby frontend to `18F/spotlight/`"
disabled = false
fork = false
forks_within = 10
full_name = "18F/Spotlight-ui"
has_downloads = true
has_issues = true
has_pages = false
has_projects = false
has_wiki = false
homepage = ""
id = 234_602_647
language = "JavaScript"
name = "Spotlight-ui"
node_id = "MDEwOlJlcG9zaXRvcnkyMzQ2MDI2NDc="
open_issues_within = 0
private = false
pushed_within = "year"
stargazers_within = 10
topics = [ ]
updated_within = "year"
watchers_within = 10

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 6_233_994
  login = "18F"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjYyMzM5OTQ="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
