code_url = "https://github.com/18F/tdrs-app-rfq"
description = "draft RFQ for the TDRS application"
git_url = "git://github.com/18F/tdrs-app-rfq.git"
name = "tdrs-app-rfq"
organization_name = "18F"

[github]
archived = false
created_at = "2020-01-31T17:36:20Z"
default_branch = "main"
description = "draft RFQ for the TDRS application"
disabled = false
fork = false
forks_within = 10
full_name = "18F/tdrs-app-rfq"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 237_482_536
language = { }
license = { }
name = "tdrs-app-rfq"
node_id = "MDEwOlJlcG9zaXRvcnkyMzc0ODI1MzY="
open_issues_within = 10
private = false
pushed_within = "month"
stargazers_within = 10
topics = [ ]
updated_within = "month"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 6_233_994
  login = "18F"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjYyMzM5OTQ="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
