code_url = "https://github.com/18F/usda-fns-ingest"
description = "Accept datafiles for USDA's Food and Nutrition Service."
git_url = "git://github.com/18F/usda-fns-ingest.git"
name = "usda-fns-ingest"
organization_name = "18F"

[github]
archived = false
created_at = "2018-05-17T18:51:57Z"
default_branch = "master"
description = "Accept datafiles for USDA's Food and Nutrition Service."
disabled = false
fork = false
forks_within = 10
full_name = "18F/usda-fns-ingest"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 133_855_610
language = "Python"
name = "usda-fns-ingest"
node_id = "MDEwOlJlcG9zaXRvcnkxMzM4NTU2MTA="
open_issues_within = 100
private = false
pushed_within = "month"
stargazers_within = 10
topics = [ ]
updated_within = "year"
watchers_within = 10

  [github.license]
  key = "other"
  name = "Other"
  node_id = "MDc6TGljZW5zZTA="
  spdx_id = "NOASSERTION"

  [github.owner]
  gravatar_id = ""
  id = 6_233_994
  login = "18F"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjYyMzM5OTQ="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
