code_url = "https://github.com/18F/vuls"
description = "The 10x Dependency Upgrades fork of the vuls.io server. More background in the main repository. See link below."
git_url = "git://github.com/18F/vuls.git"
link_url = "https://github.com/18F/10x-dux-vuls-eval"
name = "vuls"
organization_name = "18F"

[github]
archived = false
created_at = "2020-09-24T14:31:25Z"
default_branch = "master"
description = "The 10x Dependency Upgrades fork of the vuls.io server. More background in the main repository. See link below."
disabled = false
fork = true
forks_within = 0
full_name = "18F/vuls"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = "https://github.com/18F/10x-dux-vuls-eval"
id = 298_304_638
language = "Go"
name = "vuls"
node_id = "MDEwOlJlcG9zaXRvcnkyOTgzMDQ2Mzg="
open_issues_within = 10
private = false
pushed_within = "month"
stargazers_within = 0
topics = [ ]
updated_within = "month"
watchers_within = 0

  [github.license]
  key = "agpl-3.0"
  name = "GNU Affero General Public License v3.0"
  node_id = "MDc6TGljZW5zZTE="
  spdx_id = "AGPL-3.0"

  [github.owner]
  gravatar_id = ""
  id = 6_233_994
  login = "18F"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjYyMzM5OTQ="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
