code_url = "https://github.com/18F/vuls-cloudfoundry-buildpack"
description = "The 10x Dependency Upgrades CloudFoundry buildpack to instrument integration with a vuls.io server. More background in the main repository. See link below."
git_url = "git://github.com/18F/vuls-cloudfoundry-buildpack.git"
link_url = "https://github.com/18F/10x-dux-vuls-eval"
name = "vuls-cloudfoundry-buildpack"
organization_name = "18F"

[github]
archived = false
created_at = "2020-05-28T03:16:06Z"
default_branch = "master"
description = "The 10x Dependency Upgrades CloudFoundry buildpack to instrument integration with a vuls.io server. More background in the main repository. See link below."
disabled = false
fork = false
forks_within = 0
full_name = "18F/vuls-cloudfoundry-buildpack"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = "https://github.com/18F/10x-dux-vuls-eval"
id = 267_482_041
language = "Shell"
license = { }
name = "vuls-cloudfoundry-buildpack"
node_id = "MDEwOlJlcG9zaXRvcnkyNjc0ODIwNDE="
open_issues_within = 10
private = false
pushed_within = "month"
stargazers_within = 0
topics = [ ]
updated_within = "month"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 6_233_994
  login = "18F"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjYyMzM5OTQ="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
