code_url = "https://github.com/OpenEugene/bringbot"
description = 'BRING "Will it Reuse" App'
git_url = "git://github.com/OpenEugene/bringbot.git"
name = "bringbot"
organization_name = "Open Eugene"

[github]
archived = false
created_at = "2020-09-30T21:45:53Z"
default_branch = "master"
description = 'BRING "Will it Reuse" App'
disabled = false
fork = false
forks_within = 0
full_name = "OpenEugene/bringbot"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 300_070_913
language = { }
name = "bringbot"
node_id = "MDEwOlJlcG9zaXRvcnkzMDAwNzA5MTM="
open_issues_within = 0
private = false
pushed_within = "month"
stargazers_within = 0
topics = [ ]
updated_within = "month"
watchers_within = 0

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 37_278_948
  login = "OpenEugene"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjM3Mjc4OTQ4"
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
