code_url = "https://github.com/OpenEugene/local-safety-net"
description = "Asset directory and map template for your local community"
git_url = "git://github.com/OpenEugene/local-safety-net.git"
name = "local-safety-net"
organization_name = "Open Eugene"

[github]
archived = false
created_at = "2020-08-18T15:09:59Z"
default_branch = "master"
description = "Asset directory and map template for your local community"
disabled = false
fork = false
forks_within = 0
full_name = "OpenEugene/local-safety-net"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 288_489_185
language = "HTML"
name = "local-safety-net"
node_id = "MDEwOlJlcG9zaXRvcnkyODg0ODkxODU="
open_issues_within = 10
private = false
pushed_within = "year"
stargazers_within = 10
topics = [ ]
updated_within = "year"
watchers_within = 10

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 37_278_948
  login = "OpenEugene"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjM3Mjc4OTQ4"
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
