code_url = "https://github.com/OpenEugene/local-take-out"
description = "listing of resturants and a map so small businesses can stay open and feed folks during the pandemic."
git_url = "git://github.com/OpenEugene/local-take-out.git"
name = "local-take-out"
organization_name = "Open Eugene"
topics = [ "covid19" ]

[github]
archived = false
created_at = "2020-04-02T19:19:22Z"
default_branch = "master"
description = "listing of resturants and a map so small businesses can stay open and feed folks during the pandemic."
disabled = false
fork = false
forks_within = 0
full_name = "OpenEugene/local-take-out"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 252_545_875
language = { }
name = "local-take-out"
node_id = "MDEwOlJlcG9zaXRvcnkyNTI1NDU4NzU="
open_issues_within = 100
private = false
pushed_within = "year"
stargazers_within = 0
topics = [ "covid19" ]
updated_within = "year"
watchers_within = 0

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 37_278_948
  login = "OpenEugene"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjM3Mjc4OTQ4"
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
