code_url = "https://github.com/OpenEugene/Mortuary-Mapper"
description = "Mapping Mortuary Plot Data"
git_url = "git://github.com/OpenEugene/Mortuary-Mapper.git"
name = "Mortuary-Mapper"
organization_name = "Open Eugene"

[github]
archived = false
created_at = "2020-01-22T01:50:18Z"
default_branch = "master"
description = "Mapping Mortuary Plot Data"
disabled = false
fork = false
forks_within = 0
full_name = "OpenEugene/Mortuary-Mapper"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 235_478_704
language = { }
name = "Mortuary-Mapper"
node_id = "MDEwOlJlcG9zaXRvcnkyMzU0Nzg3MDQ="
open_issues_within = 10
private = false
pushed_within = "year"
stargazers_within = 0
topics = [ ]
updated_within = "year"
watchers_within = 0

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 37_278_948
  login = "OpenEugene"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjM3Mjc4OTQ4"
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
