code_url = "https://github.com/OpenEugene/virtual-town-square"
description = "locally hosted videoconferencing solutions for public and civic projects."
git_url = "git://github.com/OpenEugene/virtual-town-square.git"
name = "virtual-town-square"
organization_name = "Open Eugene"

[github]
archived = false
created_at = "2020-04-08T23:09:10Z"
default_branch = "master"
description = "locally hosted videoconferencing solutions for public and civic projects."
disabled = false
fork = false
forks_within = 0
full_name = "OpenEugene/virtual-town-square"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 254_220_795
language = { }
name = "virtual-town-square"
node_id = "MDEwOlJlcG9zaXRvcnkyNTQyMjA3OTU="
open_issues_within = 10
private = false
pushed_within = "year"
stargazers_within = 0
topics = [ ]
updated_within = "year"
watchers_within = 0

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 37_278_948
  login = "OpenEugene"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjM3Mjc4OTQ4"
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
