code_url = "https://github.com/code-for-nashville/covid-19-deliveries"
description = "Looking for Project leads..."
git_url = "git://github.com/code-for-nashville/covid-19-deliveries.git"
link_url = "https://github.com/code-for-nashville/covid-19-deliveries/wiki"
name = "covid-19-deliveries"
organization_name = "Code for Nashville"

[github]
archived = false
created_at = "2020-04-05T14:46:26Z"
default_branch = "master"
description = "Looking for Project leads..."
disabled = false
fork = false
forks_within = 0
full_name = "code-for-nashville/covid-19-deliveries"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = "https://github.com/code-for-nashville/covid-19-deliveries/wiki"
id = 253_258_064
language = { }
license = { }
name = "covid-19-deliveries"
node_id = "MDEwOlJlcG9zaXRvcnkyNTMyNTgwNjQ="
open_issues_within = 0
private = false
pushed_within = "year"
stargazers_within = 10
topics = [ ]
updated_within = "year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 8_493_450
  login = "code-for-nashville"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjg0OTM0NTA="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
