code_url = "https://github.com/codeforpdx/dreamfill"
description = "A web tool for filling out DACA paperwork"
git_url = "git://github.com/codeforpdx/dreamfill.git"
name = "dreamfill"
organization_name = "Code for PDX"

[github]
archived = false
created_at = "2020-07-23T03:47:02Z"
default_branch = "master"
description = "A web tool for filling out DACA paperwork"
disabled = false
fork = false
forks_within = 10
full_name = "codeforpdx/dreamfill"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 281_843_870
language = "CSS"
name = "dreamfill"
node_id = "MDEwOlJlcG9zaXRvcnkyODE4NDM4NzA="
open_issues_within = 0
private = false
pushed_within = "year"
stargazers_within = 0
topics = [ ]
updated_within = "year"
watchers_within = 0

  [github.license]
  key = "mit"
  name = "MIT License"
  node_id = "MDc6TGljZW5zZTEz"
  spdx_id = "MIT"

  [github.owner]
  gravatar_id = ""
  id = 39_497_980
  login = "codeforpdx"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjM5NDk3OTgw"
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
