code_url = "https://github.com/Code-For-Chicago/codeofconduct"
description = "Our Code of Conduct"
git_url = "git://github.com/Code-For-Chicago/codeofconduct.git"
name = "codeofconduct"
organization_name = "Code for Chicago"

[github]
archived = false
created_at = "2017-08-31T23:48:50Z"
default_branch = "master"
description = "Our Code of Conduct"
disabled = false
fork = true
forks_within = 10
full_name = "Code-For-Chicago/codeofconduct"
has_downloads = true
has_issues = false
has_pages = false
has_projects = true
has_wiki = true
homepage = ""
id = 102_054_968
language = "HTML"
license = { }
name = "codeofconduct"
node_id = "MDEwOlJlcG9zaXRvcnkxMDIwNTQ5Njg="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 0
topics = [ ]
updated_within = "over_a_year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 31_515_336
  login = "Code-For-Chicago"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjMxNTE1MzM2"
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
