code_url = "https://github.com/codeformunich/FinderAppGenerator"
git_url = "git://github.com/codeformunich/FinderAppGenerator.git"
name = "FinderAppGenerator"
organization_name = "OK Lab München"

[github]
archived = false
created_at = "2015-02-21T15:31:02Z"
default_branch = "master"
description = { }
disabled = false
fork = false
forks_within = 10
full_name = "codeformunich/FinderAppGenerator"
has_downloads = true
has_issues = true
has_pages = false
has_projects = true
has_wiki = true
homepage = { }
id = 31_129_759
language = "Python"
license = { }
name = "FinderAppGenerator"
node_id = "MDEwOlJlcG9zaXRvcnkzMTEyOTc1OQ=="
open_issues_within = 0
private = false
pushed_within = "over_a_year"
stargazers_within = 10
topics = [ ]
updated_within = "over_a_year"
watchers_within = 10

  [github.owner]
  gravatar_id = ""
  id = 8_250_305
  login = "codeformunich"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjgyNTAzMDU="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
