code_url = "https://github.com/CodeForAfrica/WB-DSDGs-AQ-MAP"
git_url = "git://github.com/CodeForAfrica/WB-DSDGs-AQ-MAP.git"
name = "WB-DSDGs-AQ-MAP"
organization_name = "Code for Nigeria"

[github]
archived = false
created_at = "2020-09-02T09:30:34Z"
default_branch = "master"
description = { }
disabled = false
fork = false
forks_within = 0
full_name = "CodeForAfrica/WB-DSDGs-AQ-MAP"
has_downloads = true
has_issues = true
has_pages = true
has_projects = true
has_wiki = true
homepage = { }
id = 292_239_129
language = "JavaScript"
license = { }
name = "WB-DSDGs-AQ-MAP"
node_id = "MDEwOlJlcG9zaXRvcnkyOTIyMzkxMjk="
open_issues_within = 0
private = false
pushed_within = "year"
stargazers_within = 0
topics = [ ]
updated_within = "year"
watchers_within = 0

  [github.owner]
  gravatar_id = ""
  id = 2_786_364
  login = "CodeForAfrica"
  node_id = "MDEyOk9yZ2FuaXphdGlvbjI3ODYzNjQ="
  site_admin = false
  type = "Organization"

  [github.permissions]
  admin = false
  pull = true
  push = false
