code_url = "https://github.com/citizen-input-project"
description = "A crowdsourcing platform for discovering great new candidates for public office and a real-time report of each candidate's relative popularity."
link_url = "http://www.citizeninput.org/"
name = "Citizen Input"
organization_name = "Open Seattle"
status = "in progress"
