code_url = "https://github.com/DemocracyLab"
description = "Participation environment for users, developers, and supporters of Civic Tech"
link_url = "http://www.democracylab.org"
name = "DemocracyLab"
organization_name = "Open Seattle"
status = "live/in progress"
