code_url = "https://github.com/popuparcade"
description = "Come help us create arcade machines that are designed to be played by residents of the area. See more at: http://popuparcade.org/"
link_url = "http://popuparcade.org"
name = "Popup Arcade"
organization_name = "Open Seattle"
status = "live/ongoing"
