code_url = "https://github.com/seattleio"
description = "A guide to Seattle neighborhoods & communities."
link_url = "http://seattle.io"
name = "seattle.io"
organization_name = "Open Seattle"
status = "in progress"
