code_url = "http://seattlewiki.net/Open_Data_Resources"
description = "An inventory of the most interesting data available from data.seattle.gov"
name = "Seattle Data Inventory"
organization_name = "Open Seattle"
