code_url = "https://github.com/livingwa"
description = "Goal is to provide a dashboard to access & visualize open data for homelessness"
link_url = "livingwa.github.io"
name = "Washington Homelessness"
organization_name = "Open Seattle"
